### ISSUE TITLE
Картинка-заглушка

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#10]
https://github.com/yndx-shri-reviewer/task-1/blob/master/assets/images/image-placeholder-primary.svg
Вот эта картинка должна быть вставлена в разметку svg? Или можно в качестве background-image эту картинку использовать?

**Comment by yndx-shri-reviewer** [comment]
Картинка эта, и вы можете использовать ее в качестве background-image.
