### ISSUE TITLE
Главная страница. Выравнивание layout_container

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#101]
На скриншотах после теста блоки сплющиваются и смещаются так, будто не задана ширина max-width. В стилях я проверила, она задается в layout__container_align_center. Верстка сетки сделана на display: grid.
Локально на страницу для секции с блоком payment и warning главной страницы падаю такой json
```
{
            block: 'layout',
            elem: 'container',
            mods: { 'align': 'center', 'size': 'm' },
            content: [{
                block: 'section',
                mods: { 'indent-b': 'xxl' },
                content: {
                    block: 'grid', 
                    mods: { 'm-columns': '10', 'col-gap': 'full' },
                    content: [
                        {
                            block: 'grid',
                            elem: 'fraction',
                            mods: { 'm-col': 5 },
                            ...
                        },
                        {
                            block: 'grid',
                            elem: 'fraction',
                            mods: { 'm-col': 5 },
                            ...
                        },
                    ]
                }
            }],
        },
```

При этом локально страница выглядит так:
![main_local](https://user-images.githubusercontent.com/9385858/61589954-f2a96d00-abb9-11e9-80f4-1f30f51f33c4.PNG)

А на тестах съехало так, будто и нет вовсе layout__container
![main_desctop](https://user-images.githubusercontent.com/9385858/61589968-1a003a00-abba-11e9-9db5-9c2bd6d85e82.PNG)

Подскажите, пожалуйста, может не так json как-то передаю или верстка на grid не поддерживается или что еще? Может кто-то сталкивался с такой же проблемой?

**Comment by Hakkoid** [comment]
Верстка на гридах поддерживается, если бы не применялся max-width, то все элементы расширились бы на полную ширину страницы. Может быть шаблонизатор не правильно миксует, а может быть проблемы в json теста, я сделал так, что бы миксы работали для массива или объекта

**Comment by AlexandraSmirnova** [comment]
миксы у меня тоже работают и для массива, и для объекта. но вот интересно, а устанавливается ли
grid__fraction, если элемент должен занять не 1/10-ую сетки, а половину?

**Comment by Hakkoid** [comment]
а моды у вас могут числа принимать?

**Comment by AlexandraSmirnova** [comment]
да, с числами без проблем.
Возможно в json не передается grid__fraction_m-col_5, чтобы растянуть элементы, и они поэтому занимают только 1 часть сетки

**Comment by Hakkoid** [comment]
вчера у меня все работало на тестах, так что думаю дело не в этом

**Comment by Hakkoid** [comment]
index и content прошли проверку, на других страницах только текст съехал на 2-4 пикселя, в остальном все ок

**Comment by AlexandraSmirnova** [comment]
ясно, спасибо. скорей всего у меня где-то в верстке что-то не так.

**Comment by AlexandraSmirnova** [comment]
разобралась, ошибка была в template-engine, там elemMods игнорировались в одном месте)
