### ISSUE TITLE
.theme_color_project-default

### ISSUE THREAD

**Issue by Glazomer** [yndx-shri-reviewer/task-1#102]
Как я понял, вы хотите чтобы я сделал это в стиле БЭМ, правильно?
После того как BEMJSON проходит через скрипт выходят HTML блоки с классами, благодаря которым они и стилизуются.
Но теперь вопрос, что значит "акцентный" и "бордерный"? Бордерный - это цвет границ? Что тогда значит Акцентный? 
```
Значения фонов блоков:
- дефолтный #FFFFFF;
- акцентный #0056B3;
- бордерный #000000. 
```

**Comment by VladislavYeremeyev** [comment]
Вот [здесь](https://github.com/yndx-shri-reviewer/task-1/issues/17) ответили на этот вопрос. Также эта тема поднималась в трансляции с ответами на вопросы.

**Comment by Glazomer** [comment]
А по ссылке ответа так не дано, размытое гуманитарное понятие "Привлечения внимания", что это значит?! Что конкретно требуется? Я знаю как работаем модель БЭМ, и там нет никаких "Привлечения внимания", есть Блок, элемент и модификатор который задает конкретные CSS стили.
Можно ссылку на трансляцию или хотя бы где её искать?

**Comment by VladislavYeremeyev** [comment]
https://youtu.be/XpxxRG_xOyk - трансляция
Это термины дизайн-системы, и, думаю, их не стоит привязывать к БЭМ. Цвет привлечения внимания, например, используется в кнопках.
