### ISSUE TITLE
Функция шаблонизации корректно отрабатывает только на одной странице

### ISSUE THREAD

**Issue by Darhild** [yndx-shri-reviewer/task-1#103]
Функция шаблонизации корректно отрабатывает страницу index и падает в автотестах на всех других с сообщением, что obj, подаваемый в функцию, равен null (локально везде отрабатывает правильно). Никак не могу понять, в чём между ними разница - в моём представлении, функции template-engine 4 раза подаётся полный json каждой из страниц, это верно?

**Comment by neuspeed** [comment]
Вполне может быть автотест подающий пустой объект. Чтобы шаблонизатор не падал если такое случится.

**Comment by Darhild** [comment]
Я там не совсем правильно написала, ошибка в логах - Cannot read property 'block' of null, но случай пустого/несуществующего объекта или свойства "block" обрабатывается, локально функция не падает...

**Comment by danilstoyanov** [comment]
> Я там не совсем правильно написала, ошибка в логах - Cannot read property 'block' of null, но случай пустого/несуществующего объекта или свойства "block" обрабатывается, локально функция не падает...

Может быть тогда стоит, обрабатывать ситуацию, когда ```block === null``` ? По идее, достаточно одной дополнительной проверки, которая поможет игнорировать такие блоки.

**Comment by Darhild** [comment]
Указала ещё эту ситуацию явно - нет, увы, не помогает.

**Comment by yndx-shri-reviewer** [comment]
> в моём представлении, функции template-engine 4 раза подаётся полный json каждой из страниц, это верно?

Да, так и есть

**Comment by Darhild** [comment]
Спасибо большое за советы, добавила вместо вывода ошибки другое действие, и функция заработала.
