### ISSUE TITLE
Будет ли разбор задания? И как все же нужно было правильно выравнивать текст?

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#105]
Прием заданий закончился, но интересно узнать, как все же текст должен был правильно выравниваться относительно "line-height".  Возможно, это вы расскажете в разборе задания, было бы здорово. В моем случае 1px сыграл ключевую роль.

Изначально мне показалось логичным, что текст должен вертикально выравниваться строго по центру .
То есть если высота строки у нас a = 21px, высота текста у нас b = 8px, то отступы будут равные 
`(a - b) / 2 = 7.5px `

Так как результат не получился целочисленным, то также показалось логичным если отступы будут отличаться в 1px. В данном примере получается это 7px и 6px. И 2 варианта:
бОльший отступ наверху (1), либо внизу (2). 
С отступом большим внизу (2) почти никакие тесты не прошли, в отличие от обратной ситуации (1). Пробовала сделать разницу и более чем в 1px.

![test](https://user-images.githubusercontent.com/9385858/62211902-5d238f80-b3a8-11e9-94b9-382a765b2060.PNG)

![product_mobile](https://user-images.githubusercontent.com/9385858/62212175-e5099980-b3a8-11e9-80bc-ada2e4581356.png)

На скрине уже финальный тест, не прошла только одна страница (почему-то в самом-самом последнем именно мобильная версия, до этого в десктопе тоже были расхождения в тексте). И способа поправить каким-нибудь хаком, не поломав при этом остальные тесты, я уже не нашла. Причем видно, что разница у заголовка не 1 px, а скорее 2px. Что забавно, разница пропадала у заголовка, когда проверяла вариант противоположный (2). Даже решила, что возможно ошиблась в марджинах у заголовков, но нет, они соответствовали спецификации.

**Comment by Hakkoid** [comment]
я текст трансформами выравнивал, некоторые заголовки по пикселю двигал и все сошлось, во всяком случае в тестах

**Comment by yndx-shri-reviewer** [comment]
Разбор заданий будет в сентябре.

**Comment by vaiil** [comment]
Я изначально сделал на флексах с выравниванием посередине (align-items), а затем сдвигал margin-top-ом для каждого размера текста отдельно. На сколько помню эти сдвиги больше нигде не переопределял.
