### ISSUE TITLE
Кликабельная область для раскрытия аккордеона в блоке History

### ISSUE THREAD

**Issue by Astarta0** [yndx-shri-reviewer/task-1#11]
Аккордеон должен раскрываться при клике на всю строку в блоке, или по клику на выделенную область на скриншоте?
Или допускается выбрать самому?

![2019-06-17 (2)](https://user-images.githubusercontent.com/11741142/59623246-5dd7cd80-913c-11e9-82ff-f6e99a1cb630.png)

**Comment by yndx-shri-reviewer** [comment]
На всю строку видимой области
