### ISSUE TITLE
Разная высота блока Event на странице content и в спецификации компонента

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#12]
![image](https://user-images.githubusercontent.com/18240896/59635776-ad2cf680-915a-11e9-87f1-9f28666d5432.png)
В требованиях к компоненту написано, что минимальная высота должна быть равна 333px
В макете, который нужно собрать, данный блок имеет размер 275px
![image](https://user-images.githubusercontent.com/18240896/59635875-e4030c80-915a-11e9-94bc-1bf99269df64.png)
Какая высота должна в итоге получится?
Итоговое тестирование собранного макета будет основываться на сопоставлении скриншотов, чтобы было pixel perfect?

**Comment by Ren4ik336** [comment]
![event](https://user-images.githubusercontent.com/33181633/59642114-78299f80-916c-11e9-86bd-811763c5b2ef.png)
Если я правильно понял о чем вы говорите, то высота блока мероприятия (event) составляет 333 px. возможно вы ошиблись в измерениях. Перепроверте скриншот расположенный по ссылке в ТЗ.

**Comment by danilstoyanov** [comment]
@Ren4ik336 верно. А теперь попробуйте пожалуйста сделать измерения на странице https://user-images.githubusercontent.com/18240896/59635875-e4030c80-915a-11e9-94bc-1bf99269df64.png
Которую нужно собрать из компонентов

**Comment by vaiil** [comment]
Та же ситуация и с другими блоками, на скрине блока payment он имеет высоту 356px вместе с границами, на скрине страницы index - 335.

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Мы обновили скриншоты блоков и страниц и дополнили описания блоков.
