### ISSUE TITLE
Верстка текста

### ISSUE THREAD

**Issue by vaiil** [yndx-shri-reviewer/task-1#13]
Должны ли свойства текста (размер и межстрочный интервал) быть реализованы через свойства line-height и font-size, или же блок "текст" может быть реализован иначе (например, flexbox-ами)?

**Comment by yndx-shri-reviewer** [comment]
Мы задаем в условии только внешний вид и структуру блоков. С точки зрения реализации на CSS вы можете использовать любые свойства и технологии, какие сочтете нужными.
