### ISSUE TITLE
Куда реализовать контентные блоки

### ISSUE THREAD

**Issue by KognitivnayaBuena** [yndx-shri-reviewer/task-1#15]
В задании во втором пункте показаны скриншоты контентных блоков, получается их нужно где-то реализовать в виде html? Но в итоговой папке build не указано про блоки, там должны быть файлы стилей, скриптов и шаблонизатора

**Comment by korolr** [comment]
На стриме говорили что это только для вашего удобства, для прохождения тестов должно быть достаточно стилей, скриптов и шаблонизатора

**Comment by yndx-shri-reviewer** [comment]
@korolr совершенно правильно ответил
