### ISSUE TITLE
Реализация блока цветовой темы

### ISSUE THREAD

**Issue by juliaovod** [yndx-shri-reviewer/task-1#16]
Здравствуйте!

В задании указано, что цветовая тема устанавливается путем миксования, например, элемент `<div class="card_border_all theme_color_project-default" />` имеет рамку в соответствии с темой по умолчанию, но сам модификатор `theme_color_project-default` не имеет никакого описания (так как название переменной напрямую не относится к CSS-свойству), то есть это только переменная, в таком случае придется описывать возможные варианты темы для самого блока `card_border_all`.

Скажите, пожалуйста, правильно ли я поняла реализацию цветовой темы и, если нет, то в каком направлении необходимо двигаться?

**Comment by yndx-shri-reviewer** [comment]
Мы не даем подсказок по выполнению задания. Существует несколько вариантов реализации тем как с использованием css-переменных, так и без них. Вам необходимо найти один или несколько и выбрать оптимальный
