### ISSUE TITLE
Переменные состояний фонов блоков и текстов в блоке theme

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#17]
Самое начало первого задания: "_Блок theme отвечает за глобальные переменные отступов, цветов и типографики. Каждый модификатор блока участвует в формировании внешнего вида интерфейса. Переменные, находящиеся в теме, пробрасываются во все блоки._".

Что это значит? Что значит, что нужно использовать переменные? Дальше повсюду в тексте ссылаются на эти переменные. Или переменная это просто абстракция, которая означает, что нужно реализовать CSS-свойства, которые задаются переменными, как угодно, на свой вкус (миксы, css-наследование и т.д.)?

Насчет фонов блоков
1. акцентный - это hover?
2. бордерный - это border-color?

**Comment by juliaovod** [comment]
В онлайн консультации по заданию кураторы сказали, что переменные темы не соотносятся с CSS-свойствами напрямую, то есть бордерный цвет не означает `border-color`, но я могу ошибаться, поэтому будем ждать ответа.

**Comment by SkyFlame00** [comment]
> В онлайн консультации по заданию кураторы сказали, что переменные темы не соотносятся с CSS-свойствами напрямую, то есть бордерный цвет не означает `border-color`, но я могу ошибаться, поэтому будем ждать ответа.

Кстати, кажется, наши вопросы примерно об одном и том же. Но я в ступоре из-за этой неоднозначности, поэтому даже этого понять точно не могу.

**Comment by Sindr0me** [comment]
> Самое начало первого задания: "_Блок theme отвечает за глобальные переменные отступов, цветов и типографики. Каждый модификатор блока участвует в формировании внешнего вида интерфейса. Переменные, находящиеся в теме, пробрасываются во все блоки._".
> 
> Что это значит? Что значит, что нужно использовать переменные? Дальше повсюду в тексте ссылаются на эти переменные. Или переменная это просто абстракция, которая означает, что нужно реализовать CSS-свойства, которые задаются переменными, как угодно, на свой вкус (миксы, css-наследование и т.д.)?
> 
> Насчет фонов блоков
> 
> 1. акцентный - это hover?
> 2. бордерный - это border-color?

Вряд ли это ховер-эффект. Он используется, например, в блоке buttonкак фон бекграунда.

**Comment by kaban270790** [comment]
Как я понял, `акцентный` - т.е. цвет привлечения внимания, к примеру цвет фона кнопки формы

**Comment by yndx-shri-reviewer** [comment]
> Как я понял, `акцентный` - т.е. цвет привлечения внимания, к примеру цвет фона кнопки формы

Да. Вы правы. Это цвет привлечения внимания. hover в макете нигде не задается.

> Самое начало первого задания: "_Блок theme отвечает за глобальные переменные отступов, цветов и типографики. Каждый модификатор блока участвует в формировании внешнего вида интерфейса. Переменные, находящиеся в теме, пробрасываются во все блоки._".
> 
> Что это значит? Что значит, что нужно использовать переменные? Дальше повсюду в тексте ссылаются на эти переменные. Или переменная это просто абстракция, которая означает, что нужно реализовать CSS-свойства, которые задаются переменными, как угодно, на свой вкус (миксы, css-наследование и т.д.)?
> 
> Насчет фонов блоков
> 
> 1. акцентный - это hover?
> 2. бордерный - это border-color?

Мы не даем подсказок по выполнению задания. Существует несколько вариантов реализации тем как с использованием css-переменных, так и без них. Вам необходимо найти один или несколько и выбрать оптимальный
