### ISSUE TITLE
Обнуление margin у body и тестирование

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#19]
Нужно ли обнулять стандартный margin у body? В среде тестирования это свойство обнулено или нет?

**Comment by yndx-shri-reviewer** [comment]
встречный вопрос: как body может повлиять на состовляющие дизайн-системы?

**Comment by danilstoyanov** [comment]
@yndx-shri-reviewer после просмотра видео с ответами на вопросы этот issue потерял актуальность, как я понял body трогать не нужно.
