### ISSUE TITLE
Блок history

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-1#20]
элемент - history__details [объединяет блок времени, логотипа и текста] - в него входит отдельный блок текста в конце строки транзакции? Или этот крайний справа блок текста является непосредственно дочерним элементу history__show?
также вопрос по миксованиям list__item_indent-t и list__item_indent_b, при их добавлении в соответствии со спецификацией к элементам history__show и history__actions, сборка перестает сходиться с представленным макетом (строка транзакции становится шире, чем на макете), они действительно там нужны или я неправильно их миксую?

**Comment by Astarta0** [comment]
У меня тоже вопросы по этому блоку, тоже не сошелся, несколько раз переделывала, напишу тоже сюда:
1. Я считаю, что в подсказке для блока history указан ненужный модификатор list__item_indent-t_m на элементе __show
        ```- history__show (e-accordion__short list__item_vertical-align_center list__item_indent-t_m)[контейнер для видимой части строки]```
    Т.к. у оборачивающего его элемента history__transaction задан padding c помощью модификатора  list__item_space-a_l.
    И По наложению скриншотов - соответствие только при наличии отступа у history__transaction.

2. На элементе history__hide в подсказке задан модификатор list__item_indent-t_m, при наложении скриншотов было несоответствие, сюда больше подошел list__item_indent-t_l.

3. У меня так и не сошлось, может я тоже неправильно миксую, или все-таки скрин блока такой?
![2019-06-20](https://user-images.githubusercontent.com/11741142/59848966-20a75180-936f-11e9-960e-cc4536bd9536.png)

**Comment by danilstoyanov** [comment]
Расширю тред дополнительным вопросом.
![image](https://user-images.githubusercontent.com/18240896/59980917-39c93000-9605-11e9-867d-33475e581c16.png)
Обратите внимание на подчёркнутые экшны.
В спецификации компонента написано:
![image](https://user-images.githubusercontent.com/18240896/59980920-52d1e100-9605-11e9-95fd-519f1cff821d.png)

Вопрос:
Какие слова в экшнах следует использовать:
```m + m или l + m```
?

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Мы обновили скриншоты блоков и страниц и дополнили описание блоков.

Что касается модификаторов list__item_indent-t и list__item_indent_b, то здесь ошибки нет. Они должны быть, и средствами CSS вы можете получить верстку, соответствующую описанию и скриншотам.

**Comment by SkyFlame00** [comment]
> Мы обновили скриншоты блоков и страниц и дополнили описание блоков.
> 
> Что касается модификаторов list__item_indent-t и list__item_indent_b, то здесь ошибки нет. Они должны быть, и средствами CSS вы можете получить верстку, соответствующую описанию и скриншотам.

Так и что вы предлагаете делать-то? Вот возьмем хотя бы `history__show`. Если по картинке измерять верхний отступ до любого из `brand_logo`, то получим 20px. Если следовать описанию задания, то получим следующее: внутренние отступы у `history__transaction` (элемент, в который вкладывается `history__show`) равны 20px, модификатор `list__item_indent-t_m` у самого `history__show` дает еще 16px. Итого получаем 20 + 16 = 36px, а на картинке, напомню, 20px. Или я как-то неправильно вложил элементы друг в друга, неправильно сделал миксы или что угодно еще? Я не знаю, может, нужно задать отрицательные отступы у элементов в `history.css`?

**Comment by alexeyshilyaev** [comment]
> Мы обновили скриншоты блоков и страниц и дополнили описание блоков.
> 
> Что касается модификаторов list__item_indent-t и list__item_indent_b, то здесь ошибки нет. Они должны быть, и средствами CSS вы можете получить верстку, соответствующую описанию и скриншотам.

Если использовать пиксель перфект, для элемента actions подходят только такие отступы:
Внешний верхний – s
Внешний нижний – xs.

Внешний нижний с размером l не подходит! (.list__item_indent-b_l)

**Comment by Astarta0** [comment]
Как-то странно это..ставить модификаторы, стили которых нужно переписывать. А как же переиспользование и вот это вот все?
Уже досточно много мест, где снача я добавила от себя, что было "логично" на мой взгляд, но не встречалось в описании блоков, а теперь все это заменяется на связанные селекторы и переопределение стилей "лишних" модификаторов :с

**Comment by yndx-shri-reviewer** [comment]
> Как-то странно это..ставить модификаторы, стили которых нужно переписывать. А как же переиспользование и вот это вот все?
> Уже досточно много мест, где снача я добавила от себя, что было "логично" на мой взгляд, но не встречалось в описании блоков, а теперь все это заменяется на связанные селекторы и переопределение стилей "лишних" модификаторов :с

При реализации этого блока вам не нужно ничего переопределять. Все переиспользуется одним и тем же образом для любого элемента блока list.

**Comment by shishkinilya** [comment]
Расстояние от логотипа до верхней границы 20px, а до нижней 24px, вместо модификатора list__item_indent-t_m больше подходит какой нибудь list__item_indent_b_xxs, который бы добавил 4px отступа и в итоге получилось бы 20px внутреннего отступа от list__item_space-a_l + 4px внешнего отступа от list__item_indent_b_xxs. Но модификатора list__item_indent_b_xxs вобще нету)
Пока я тоже вижу выход только перебить стили для history__show, чтобы убрать margin от margin от list__item_indent-t_m.

**Comment by kaban270790** [comment]
> Расстояние от логотипа до верхней границы 20px, а до нижней 24px, вместо модификатора list__item_indent-t_m больше подходит какой нибудь list__item_indent_b_xxs, который бы добавил 4px отступа снизу вместо 16px отступа сверху и в итоге получилось бы 20px внутреннего отступа от list__item_space-a_l + 4px внешнего отступа от list__item_indent_b_xxs. Но модификатора list__item_indent_b_xxs вобще нету)
> Пока я тоже вижу выход только перебить стили для history__show, чтобы убрать margin от margin от list__item_indent-t_m.

плюсую, тоже переопределяю стили, хотя не вижу это логичным
