### ISSUE TITLE
Значения grid_col-gap

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-1#21]
Собирая страницу index,, столкнулся, что промежуток между блоками product на макете меньше, чем в моей сборке, хотя я брал минимально возможный - grid_col-gap_half. Возникло ощущения, что не хватает еще одного значения модификатора - а именно grid_col-gap_one-thirds - т.е. одна треть полного интервала. с таким значением сборка ложится на макет

**Comment by bo4arovpavel1989** [comment]
![Screenshot_2019-06-20 Screenshot(1)](https://user-images.githubusercontent.com/23580188/59856503-b21ebf80-937f-11e9-94ba-d03151f0eeea.png)

впрочем наблюдается несоответствие с картинкой на блоку продукта, хотя в элемент по спецификации замиксован card__content_space-a_m

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Мы обновили скриншоты блоков и страниц и дополнили описание блоков. Сверьтесь, пожалуйста, ещё раз.
