### ISSUE TITLE
Блок collect

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-1#22]
В спецификации не указаны названия элемента прогресс-бара и модификаций, определяющих его заполнение. Чтобы пройти автотесты я не могу придумать свои названия этих моментов, т.к. они могут не совпасть с теми,которые используются в вашей сборке

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответ на данный вопрос в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Спасибо за вопрос. Дополнили описание блока.

**Comment by SkyFlame00** [comment]
В блоке с текстом (`card__footer`) заданы внутренние отступы в 20px (`card__footer_space-a_l`). На деле, если измерять от левой белой границы до текста, получится 16px. Тогда тут скорее подходит `space-a_m`. Это ошибка?

**Comment by yndx-shri-reviewer** [comment]
> В блоке с текстом (`card__footer`) заданы внутренние отступы в 20px (`card__footer_space-a_l`). На деле, если измерять от левой белой границы до текста, получится 16px. Тогда тут скорее подходит `space-a_m`. Это ошибка?

Обновили скриншот. Проверьте, пожалуйста
