### ISSUE TITLE
Инверсная тема. Смена темы на всей странице. Заглушка Image.

### ISSUE THREAD

**Issue by Astarta0** [yndx-shri-reviewer/task-1#23]
Хочу уточнить, что 
1. элемент Image с белой картинкой - в инверсной теме, как написано в задании
![2019-06-20 (5)](https://user-images.githubusercontent.com/11741142/59856439-94515a80-937f-11e9-9902-4a691c62214b.png)
2. Тогда следовательно, в карточке Product в дефолтной теме, мы делаем заглушку в инверсной теме в соответствии со скриншотом
![2019-06-20 (7)](https://user-images.githubusercontent.com/11741142/59856632-fdd16900-937f-11e9-9ff9-6442049c21f5.png)

Тогда при переключении темы на всей странице с блоками надо поменять темы у таких вот зависимых от темы внутренних элементов.
Хочу убедиться, что все так, ничего не перепутано)

Если следовать такой логике, вот еще странный пример, блок Collect
```collect (card_view_default card_border_all theme theme_color_project-inverse)``` в подсказке явно задано что он выглядеть должен вот так, и на скриншотах он всегда на блоке с темной подложкой - т.е. когда на внешнем элементе тоже инверсная тема -_-
![2019-06-20 (8)](https://user-images.githubusercontent.com/11741142/59858510-c6fd5200-9383-11e9-8d7e-298c407b537b.png)
Тогда, если нужен обход элементов, у которых явно указана тема,чтобы ее сменить, именно этот блок трогать не нужно, чтобы не получилось сливания фона заглушки
**ИЛИ на этом блоке (collect ) не нужен модификатор темы**, а только на заглушке внутри него

**Comment by bo4arovpavel1989** [comment]
Вдогонку хочу уточнить, между какими темами должен переключать ползунок в хедере?

**Comment by Astarta0** [comment]
Точно сформулированный вопрос:
Какая картинка инверсная? Черный пришелец на белом или белый на черном?

![2019-06-21 002827](https://user-images.githubusercontent.com/11741142/59882672-8f120100-93bb-11e9-8412-30597e1100f5.png)

В спецификации:
 - дефолтная тема: черный на белом `image-placeholder-primary.svg`
 - инверсная: белый на черном `image-placeholder-inverse.svg`

Я считаю, что наоборот (исходя из скриншотов и логики):
 - дефолтная тема: белый на черном `image-placeholder-inverse.svg`
 - инверсная: черный на белом `image-placeholder-primary.svg`

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by vaiil** [comment]
@yndx-shri-reviewer В последних коммитах не увидел каких-либо комментариев по данному issue, стоит ли их ждать?

**Comment by shishkinilya** [comment]
+1
Оба изображения в блоках articles и collect по заданию с инверсной темой, а выглядят по разному.
![b96c0f5b4a](https://user-images.githubusercontent.com/20458127/60506772-47e71280-9ccf-11e9-8aff-e6762d7572ab.jpg)

**Comment by yndx-shri-reviewer** [comment]
> Точно сформулированный вопрос:
> Какая картинка инверсная? Черный пришелец на белом или белый на черном?
> 
> ![2019-06-21 002827](https://user-images.githubusercontent.com/11741142/59882672-8f120100-93bb-11e9-8412-30597e1100f5.png)
> 
> В спецификации:
> 
> * дефолтная тема: черный на белом `image-placeholder-primary.svg`
> * инверсная: белый на черном `image-placeholder-inverse.svg`
> 
> Я считаю, что наоборот (исходя из скриншотов и логики):
> 
> * дефолтная тема: белый на черном `image-placeholder-inverse.svg`
> * инверсная: черный на белом `image-placeholder-primary.svg`

В условии задачи не сказано, что черная картинка соответствует дефолтной теме. Это просто названия картинок. Черная - дефолтная, белая - инверсная.
Как вы могли заметить, блокам с инверсной темой может соответствовать как белая, так и черная картинка.
Ваша задача как раз и заключается в том, чтобы придумать способ правильного отображения этого блока.

> Вдогонку хочу уточнить, между какими темами должен переключать ползунок в хедере?

Ползунок переключает блоки между дефолтной и инверсной темами. Темы project-warning, project-brand, megafon-brand он не затрагивает.

**Comment by vaiil** [comment]
@yndx-shri-reviewer Тогда каким должно быть отображение по-умолчанию, то есть без стилей контекстного блока?
Также вопрос по этому:
> Блок служит для отображения изображений. Растягивается на всю ширину, имеет границу и содержит заглушку.
"Имеет границу" - это border? Про цвет фона ничего в описании блока image не сказано, следует ли из этого что background-color должен задаваться на уровне контентных блоков?

**Comment by yndx-shri-reviewer** [comment]
Сделайте дефолтной черную картинку на белом фоне.
Параметры внешнего вида блока image у вас всё равно будут прокидываться извне, поэтому это не принципиально.

**Comment by AlexandraSmirnova** [comment]
Правильно понимаю, что цвет картинки и фон вообще не зависят от того примиксовали мы к контентному блоку theme_color_project-inverse или нет? 
Или все таки зависит и в каждом блоке отдельно нужно определить какой будет вид картинки в случае примиксования инверсной темы? (В одном блоке для theme_color_project-inverse показываем белую картинку на черном, а в другом наоборот)

**Comment by yndx-shri-reviewer** [comment]
Мы обновили описание блока image и контентных блоков, в которых используется блок image.
В дефолтной теме изображение имеет черную заглушку, черную границу и белый фон. В инверсном - белую заглушку и границу и черный фон.
Задаются эти параметры темой и при необходимости переопределяются на уровне контентного блока.
