### ISSUE TITLE
Смысловой блок: warning

### ISSUE THREAD

**Issue by Sindr0me** [yndx-shri-reviewer/task-1#24]
> Смысловой блок: warning
> Примиксованные блоки паттернов
> 
> warning (informer_view_default informer_border_all)
> warning__content (informer__content_distribute_center informer__content_space-a_xxl)
> warning__button-wrapper (informer__action_distribute_center informer__action_space-a_xl)
> Вложенные контентные блоки
> 
> text text_view_primary text_size_xl
> placeholder placeholder_view_primary placeholder_size_m

1. Почему не сказано про вложенный блок `button` когда есть `warning__button-wrapper`?

2. Блоки паттерны могут существовать отдельно, вне смысловых блоков?

3. А если к блоку `warning `можно будет примиксовать все модификаторы паттерна `informer`, а не только указанные, как это будет проверяться? в таком случае стили должны примениться или нет?

**Comment by Sindr0me** [comment]
Также у вложенных контентных блоков `text` не прописан модификатор, `p, h1` и тд, Так он все же присутствует? по дефолту ведь у блока `text `нет отступов и выходит, что он прибит к `placeholder`.

**Comment by bo4arovpavel1989** [comment]
> Также у вложенных контентных блоков `text` не прописан модификатор, `p, h1` и тд, Так он все же присутствует? по дефолту ведь у блока `text `нет отступов и выходит, что он прибит к `placeholder`.

с этим сам тоже мучался, но потом понял - в общем отступы блока text (точнее у вложенных в них элементов word) определяются значением межстрочных интервалов. эмпирическим путем вывел, что текстовые блоки совпадают с макетом, если задать отступы например для размера текста s по следующей формуле:
`  .text_size_s    .text__word {

      margin-bottom: calc((var(--line-s}) - var(--text-s))/2)
      margin-top: calc((var(--line-s) - var(--text-s))/2)
}
`

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
> > Смысловой блок: warning
> > Примиксованные блоки паттернов
> > warning (informer_view_default informer_border_all)
> > warning__content (informer__content_distribute_center informer__content_space-a_xxl)
> > warning__button-wrapper (informer__action_distribute_center informer__action_space-a_xl)
> > Вложенные контентные блоки
> > text text_view_primary text_size_xl
> > placeholder placeholder_view_primary placeholder_size_m
> 
> 1. Почему не сказано про вложенный блок `button` когда есть `warning__button-wrapper`?
> 2. Блоки паттерны могут существовать отдельно, вне смысловых блоков?
> 3. А если к блоку `warning `можно будет примиксовать все модификаторы паттерна `informer`, а не только указанные, как это будет проверяться? в таком случае стили должны примениться или нет?

1. Спасибо за вопрос. Поправили описание блока.

2. С точки зрения верстки ничто не мешает им существовать отдельно. Блок list, например, и без дополнительных стилей будет отображать элементы. Но в нашем задании они всегда примиксовываются.

3. На этот вопрос ответим в ближайшее время.

**Comment by yndx-shri-reviewer** [comment]
> Также у вложенных контентных блоков `text` не прописан модификатор, `p, h1` и тд, Так он все же присутствует? по дефолту ведь у блока `text `нет отступов и выходит, что он прибит к `placeholder`.

У блока text есть модификатор type, который задает свойства параграфа и заголовков. Если он не указан, значит отступов нет.
