### ISSUE TITLE
Вложенные селекторы

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#25]
В документации к BEM есть такая секция:
![image](https://user-images.githubusercontent.com/18240896/59865919-f49dc780-9392-11e9-875d-4db5f9af1735.png)
Однако в некоторых компонентах, без вложенных селекторов у меня не получается задать правильные расстояния. Насколько сильно проверяющими карается нарушение этого правила?

**Comment by yndx-shri-reviewer** [comment]
Мы приветствуем обоснованные решения, к вложенным селекторам это тоже относится. Если вы считаете, что решение с использованием вложенного селектора является наилучшим, то используйте его.
