### ISSUE TITLE
Oграничение ширины контента Header. Переключатель темы в Header.

### ISSUE THREAD

**Issue by Astarta0** [yndx-shri-reviewer/task-1#26]
По аналогии с Footer, логично, чтобы у Header так же было ограничение 
```максимальная ширина контента — 1144px.```

Также переключатель темы есть только на index странице на скриншотах, на других страницах почему-то отсутствует.

**Comment by danilstoyanov** [comment]
> По аналогии с Footer, логично, чтобы у Header так же было ограничение
> `максимальная ширина контента — 1144px.`
Хм, там еще должны быть отступы у хедера по горизонтали. С учетом такой макисмальной ширины и отступов, логотип отъедет в сторону и визуально будет казаться что он не по сетке свёрстан.
https://github.com/yndx-shri-reviewer/task-1/blob/master/assets/screenshots/header.png

И вообще насчёт хедера и футера не очень понятно, являются ли они вложенным в блок layout или всё же являются независимыми элементами

**Comment by Ren4ik336** [comment]
Тоже появился вопрос, касающийся футера и хедера. Думаю может здесь можно организовать дизайн систему ввиде библиотеки, а вот структуру сайта сделать отдельно. Возможно не правильно представляю, но пока думаю так.

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Горизонтальные отступы будут проявляться в мобильном отображении, и это нормально.

Визуальное отображение хедера и футера определяется параметрами темы, поэтому не принципиально, отдельно ли они будут располагаться от блока layout или будут вложены в layout__container без модификаторов.
