### ISSUE TITLE
Актуальные скриншоты или проблема с отступами в сетке

### ISSUE THREAD

**Issue by Astarta0** [yndx-shri-reviewer/task-1#27]
Пытаюсь собрать страницы ориентируясь на предоставленные скриншоты (предполагаю скриншоты сделаны с эталонного варианта решения, которое будет использоваться в тестах) и у меня не сходятся размеры и отступы колонок в сетке.

В спецификации написано:

`BASE.md`
> Модификации отступов
> **xxxl: 40px;**
> .theme_gap_small — модификатор на отступ между колонками и отступами в сетке ... на десктопе имеет значение, соответствующее **xxxl-отступу**
> m-columns: 12 | 10  Количество возможных колонок при ширине экрана screen-m
> col-gap: two-thirds | full | half Отступ между колонками

`PAGES.md`
> Главная страница (index.html)
> отступы между столбцами и колонками в сетке — **full**.

Делаю вывод, что отступ между колонками равен 40px в full варианте, 20 -- half, 30 -- two-thirds.

Теперь смотрим на [скриншот](https://github.com/yndx-shri-reviewer/task-1/blob/master/assets/pages/index.png) и обнаруживаем, что там отступы совсем другие: 24px full, 12 half и т.д. Причем если смотреть на [предыдущую версию скриншота](https://github.com/yndx-shri-reviewer/task-1/blob/87b356cf4c7b97b35b556c1ab8d8a1cdce24f116/assets/pages/index.png), то там тоже другие размеры: 32px full, 16px half.

![Index Page](https://user-images.githubusercontent.com/11741142/59881003-29237a80-93b7-11e9-8be6-83519dde7a8c.png)

Я вижу два варианта:

1) Скриншоты в репозитории расходятся с теми, что будут использоваться в тестах и не актуальны, сверять по ним нельзя (но на что тогда ориентироваться?).

2) Скриншоты актуальны и автотесты будут сверять решение именно на такие размеры, значит неправильные размеры указаны в документации к блокам.

**Comment by VBagmut** [comment]
В чем проблема выбрать репозиторий в личном кабинете и проверить? Если все ОК, то тесты не упадут и он отправится на проверку человеку.

**Comment by Astarta0** [comment]
> В чем проблема выбрать репозиторий в личном кабинете и проверить? Если все ОК, то тесты не упадут и он отправится на проверку человеку.

А если не пройдут, то гадать, где проблема - в этом месте иди в других, где так же со скриншотами не сходится, потому что они "не финальные" ? И перебирать все варианты, между описанием и расходящимся скриншотом?

**Comment by geowatson** [comment]
Скриншоты не должны отражать реальность напрямую (давать актуальные размеры), для этого есть спецификации. Другое дело, когда автотесты не прогоняются именно из-за этого — тогда можно создавать issue)

**Comment by bo4arovpavel1989** [comment]
> 
> 
> Скриншоты не должны отражать реальность напрямую (давать актуальные размеры), для этого есть спецификации. Другое дело, когда автотесты не прогоняются именно из-за этого — тогда можно создавать issue)

на трансляции говорили, что проверка pixel perfect будет по эталонному отображению - а оно как раз и представлено на скриншотах

**Comment by GumerShag** [comment]
> на трансляции говорили, что проверка pixel perfect будет по эталонному отображению - а оно как раз и представлено на скриншотах

На трансляции было сказано немного иначе и меня это совсем запутало. То есть эти скриншоты не эталонные? Не ясно как можно достичь pixel perfect в таком случае
https://youtu.be/XpxxRG_xOyk?t=4925

**Comment by geowatson** [comment]
@GumerShag получается, что пока не выкатят новый PR с обновлёнными скриншотами - не эталонные

**Comment by bo4arovpavel1989** [comment]
> > на трансляции говорили, что проверка pixel perfect будет по эталонному отображению - а оно как раз и представлено на скриншотах
> 
> На трансляции было сказано немного иначе и меня это совсем запутало. То есть эти скриншоты не эталонные? Не ясно как можно достичь pixel perfect в таком случае
> https://youtu.be/XpxxRG_xOyk?t=4925

как раз после трансляции они обновили скриншоты страниц, и вроде как обновленные и являются эталоном по идее

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Мы обновили скриншоты страниц и блоков и дополнили описание некоторых блоков.
