### ISSUE TITLE
Название функции шаблонизатора

### ISSUE THREAD

**Issue by geowatson** [yndx-shri-reviewer/task-1#28]
Добрый день, как вы автотестите файл `template-engine.js`?
В названии присутствует `-`, что не дает заимпортить этот файл при помощи `import`. Возможно, я что-то неправильно делаю)

**Comment by iamgroog** [comment]
Звучит так, будто вы забыли кавычки

**Comment by geowatson** [comment]
@iamgroog можете пожалуйста привести полный кодсниппет?
`import 'template-engine' from 'template-engine.js';` ?

**Comment by Hakkoid** [comment]
может быть `import templateEngine from './template-engine.js';`

**Comment by geowatson** [comment]
> может быть import templateEngine from './template-engine.js';

Видимо, я не до конца понимал как работает `export default function`, спасибо
