### ISSUE TITLE
Блок product: проблемы с размерами, границами, отступами и box-sizing: border-box

### ISSUE THREAD

**Issue by chrstnv** [yndx-shri-reviewer/task-1#31]
По спецификации-подсказке к миксованию элементов указаны следующие модификаторы:

> product__content (card__content card__content_space-a_m)
> product__footer (card__footer card__footer_space-a_m)

то есть внутренние отступы должны быть равны `16px`.

Размер границ для блоков product, image — `3px`.

На скриншоте у блока product отступы от границы до картинки `19px`. Предполагаю, что `3px` — это белая граница картинки, на которую применена инверсная тема. 

И вроде бы все сходится, но высота картинки на скриншоте `160px`, а с условием, что у всех элементов должно быть установлено свойство `box-sizing: border-box`, получается, что граница должна учитываться в высоте картинки.
Но откуда тогда «лишние» `3px` во внутреннем отступе блока `product__content`?

Помогите, пожалуйста, разобраться.
![index_png__1230×1382__1](https://user-images.githubusercontent.com/17298953/59964467-e8884600-9509-11e9-8886-a8372dc6be65.png)
![index_png__1230×1382_](https://user-images.githubusercontent.com/17298953/59964465-e58d5580-9509-11e9-817a-1c2c42db2de4.png)

**Comment by chrstnv** [comment]
Аналогичный вопрос по блоку .warning. У него есть рамка (миксуется с `informer_border_all`), по теме `.theme_color_project-warning` она белого цвета.
Если выполнять условие про то, что у всех элементов `box-sizing: border-box`, то рамка будет учитываться в высоте блока, и блок будет визуально меньше высотой на `6px`.

**Comment by yndx-shri-reviewer** [comment]
Мы подготовим ответы на данные вопросы в ближайшие несколько дней

**Comment by yndx-shri-reviewer** [comment]
Обновили скриншоты блоков и страниц и дополнили описание блоков
