### ISSUE TITLE
Блок form: не все элементы включили в таблицу

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#32]
В описании блока form в таблице элементов только item, label, control.  А далее в описании есть еще header, content, content-item, footer.

**Comment by yndx-shri-reviewer** [comment]
Спасибо за вопрос. Дополнили описание блока.

**Comment by shishkinilya** [comment]
Помоему, не хватает описания элемента .form__control 
https://raw.githubusercontent.com/yndx-shri-reviewer/task-1/master/assets/screenshots/payment.png
Откуда брать стили для этого элемента? Как мне кажется должно быть также какая-то спецификация для этого элемента, модификаторы для высоты, ширины контрола, границы.

**Comment by AlexandraSmirnova** [comment]
как я поняла, form__control - это просто обертка. Там особо стилей не нужно, для высоты точно не нужно. Главное, чтобы внутри элементы располагались в одной строке. При этом лейбл займет 35%  ширины (судя по описанию лейбла), а инпут - оставшееся место.

**Comment by yndx-shri-reviewer** [comment]
> как я поняла, form__control - это просто обертка. Там особо стилей не нужно, для высоты точно не нужно. Главное, чтобы внутри элементы располагались в одной строке. При этом лейбл займет 35% ширины (судя по описанию лейбла), а инпут - оставшееся место.

Абсолютно верно. Эти обертки не определяют внешний вид и нужны только для того, чтобы разместить лейбл и инпут в одну строку.
