### ISSUE TITLE
Функция шаблонизации

### ISSUE THREAD

**Issue by bzrov** [yndx-shri-reviewer/task-1#33]
Не понимаю как несколько мелких блоков в более крупный кроме как не в виде bemsjon. но не понятно где применяется функция шаблонизации. То есть наша функция просто возвращает полную html разметку. Или она должно поблочно создавать каждый элемент страницы и потом его вставлять в html. Может кто объяснить что именно должна делать функция шаблонизации?

**Comment by iamgroog** [comment]
> Может кто объяснить что именно должна делать функция шаблонизации?

В [описании](https://github.com/yndx-shri-reviewer/task-1/blob/master/TEMPLATER.md#функция-шаблонизации) сказано:

> Реализовать функцию-шаблонизатор, трансформирующую JSON с конкретными блоками и элементами в валидную HTML-разметку...

И обратите внимание на [описание](https://github.com/yndx-shri-reviewer/task-1#результат) функции, она должна возвращать строку.

> \/**
> \* \@ param  {object} obj — Структура блоков интерфейса в формате BEMJSON
> \* \@ return {**string**} HTML разметка страницы
> \*/
> export default function (obj) {
>    // ...
> }
> 
> Результирующая разметка должна содержать только контент страницы и не должна содержать тэги html, head, body.

Как я понимаю способ создания разметки остается на ваш выбор.

**Comment by yndx-shri-reviewer** [comment]
Абсолютно верно. На вход принимает объект, возвращает строку с разметкой.
Вы можете как написать свою реализацию шаблонизатора, так и воспользоваться готовыми решениями.
