### ISSUE TITLE
Onoffswitch опечатка

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#35]
Ребята, будьте бдительны:
![image](https://user-images.githubusercontent.com/18240896/60124664-d5d47200-9792-11e9-8192-7e8889a3de20.png)
![image](https://user-images.githubusercontent.com/18240896/60124731-f69cc780-9792-11e9-9466-6523aae002cc.png)
Опечатка в названии класса, по логике нужно **onoffswitch** использовать

**Comment by yndx-shri-reviewer** [comment]
Поправили описание. Спасибо
