### ISSUE TITLE
Если страница < 1144px, то страница считается мобильной версией ?

### ISSUE THREAD

**Issue by disant9807** [yndx-shri-reviewer/task-1#37]
Если страница имеет разрешение меньше 1144px, то она считается мобильной версией ?

**Comment by VBagmut** [comment]
Да, в трансляции говорили что решили ограничиться одним брейкпоинтом для простоты.

**Comment by yndx-shri-reviewer** [comment]
Да, верстка для экранов шириной меньше 1144px считается мобильной.
