### ISSUE TITLE
Поддержка браузерами

### ISSUE THREAD

**Issue by Tauka** [yndx-shri-reviewer/task-1#38]
Какая ожидается поддержка браузерами? Можем ли мы смело использовать es6?

Я предполагаю что да, учитывая что в сигнатуре функции шаблонизации мы видим экспорт, а раз шаблонизатор должен работать и в браузерах, то скорее всего он будет вставляться через `<script type="module"/>`, который еще очень новый

**Comment by VBagmut** [comment]
Предпоследняя версия Chrome и 8 нода.

**Comment by yndx-shri-reviewer** [comment]
Вы можете использовать es6. Вставляться он будет не через <script type="module" />.
Мы собираем код webpack'ом перед запуском тестов, т.к. подключаем ещё нашм собственные скрипты.
