### ISSUE TITLE
warning mix

### ISSUE THREAD

**Issue by kaban270790** [yndx-shri-reviewer/task-1#39]
[Вот тут](https://github.com/yndx-shri-reviewer/task-1/blob/master/CONTENT.md#смысловой-блок-warning) в блоке `warning` не должен быть примиксован блок theme с модификатором `"color": "project-warning"`?

**Comment by kaban270790** [comment]
И так же текст `text_view_primary` text_size_xl` судя макету мне кажется должен быть еще с модификаторами `"type": "p"` и  `"align": "center"`

**Comment by SkyFlame00** [comment]
Еще плюс у informer нет модификатора `border: all`

**Comment by kucherovruslan** [comment]
Тоже заметил, что в warning непонятно что нужно миксовать. Написано warning (informer_view_default informer_border_all), но у informer вообще нет никаких модификаторов в задании, только элементы. Что с этим делать?

**Comment by kucherovruslan** [comment]
Тоже заметил про информер. Написано примиксовать warning (informer_view_default informer_border_all), но у informer нет никаких модификаторов по заданию, только элементы.

**Comment by alexeyshilyaev** [comment]
Скорее всего, нужно в informer добавить модификатор border со значением all.

**Comment by SkyFlame00** [comment]
> Скорее всего, нужно в informer добавить модификатор border со значением all.

А вот не факт, что таким самоуправством заниматься можно (интересно было бы узнать ответ яндекса). Мне логичным видится примиксовывание блока `card` с модификатором `border: all`.

**Comment by shishkinilya** [comment]
+1
Как мне кажется нужно добавить блоку informer модификатор _view_default для фона, а модификатор _border_all не нужен, т.к. если к блоку добавится граница, то блоки payment и warning не будут на одном уровне (см. скриншот)
http://joxi.ru/xAe0lGBsR5N552

**Comment by kaban270790** [comment]
> +1
> Как мне кажется нужно добавить блоку informer модификатор _view_default для фона, а модификатор _border_all не нужен, т.к. если к блоку добавится граница, то блоки payment и warning не будут на одном уровне (см. скриншот)
> http://joxi.ru/xAe0lGBsR5N552

Они на днях обновили макет этого блока отдельно, и по нему я тоже задал вопрос, там четко виднеется граница, и размер блока из-за этого стал меньше. А основной макет остался прежним. Но у меня ни с первым ни со вторым вариантом не прошел тест. Жду ответа от авторов задания

**Comment by shishkinilya** [comment]
@kaban270790 Спасибо, [вот здесь](https://raw.githubusercontent.com/yndx-shri-reviewer/task-1/master/assets/screenshots/warning.png) и правда есть четкая граница

**Comment by yndx-shri-reviewer** [comment]
Добавили в описание блока informer модификатор border_all.
