### ISSUE TITLE
Функция шаблонизации mod или mods

### ISSUE THREAD

**Issue by vaiil** [yndx-shri-reviewer/task-1#4]
Миксы задаются массивами, каждый элемент которого включает в себя название блока и/или элемента:
```
{
    block: 'my-block`,
    mix: [
        {block: 'other-block', mods: {'mod-name': 'mod-value'}},
        {block: 'other-block', elem: 'second-elem', mod: {'elem-mod-name': 'elem-mod-value'}}
    ]
}
```

В одном случае mods: `{block: 'other-block', mods: {'mod-name': 'mod-value'}},`
В другом - mod: `{block: 'other-block', elem: 'second-elem', mod: {'elem-mod-name': 'elem-mod-value'}}`

В документации: mods.

**Comment by chrstnv** [comment]
По BEMJSON модификаторы элемента задаются в свойстве elemMods, это правило сохраняется для данного задания?

**Comment by phenotropili** [comment]
Используйте elemMods, как в BEMJSON. Мы поправили этот пункт в условии.
