### ISSUE TITLE
Состояния элементов при :hover

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#40]
В задании прямо нигде не говорится  о необходимости стилизации элементов при наведении, однако в переменных цвета фигурирует ```accent-color```.

Нужно ли использовать ховер для onoffswitch, ссылок в блоке event, и в других подобных местах?

**Comment by SkyFlame00** [comment]
Здесь ответили #17

**Comment by danilstoyanov** [comment]
Точно, спасибо!
