### ISSUE TITLE
Сквозной блок header и footer

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#42]
Формулировка ```сквозной блок``` означает, что эти элементы существуют вне рамок блока layout?
![image](https://user-images.githubusercontent.com/18240896/60375293-41c40e00-9a11-11e9-8c14-3839cfbbe5dc.png)

**Comment by yndx-shri-reviewer** [comment]
Под сквозными понимаются одинаковые блоки, которые используются на всех страницах на одних и тех же местах. Как правило, это хедер, футер, какие-то меню и т.п.
