### ISSUE TITLE
блок warning

### ISSUE THREAD

**Issue by kaban270790** [yndx-shri-reviewer/task-1#45]
Сегодня обновили скриншот блока warning, как я заметил он уменьшился по высоте (6px) и ширине (1px) и добавилась граница, но на макете страницы блок в старом варианте, со старыми размерами и без границ. При чем добавление белой границы не логичное, потому что блок будет казаться меньше соседнего на белом фоне. Так же в описании по блоку `informer` не указан модификатор `border`, вообще ни одного, хотя к блоку `warning` примиксованы его стили

**Comment by yndx-shri-reviewer** [comment]
Спасибо за вопрос. Добавили модификатор informer_border_all.

**Comment by kaban270790** [comment]
@yndx-shri-reviewer Спасибо. А макет страницы `index`? Данный блок на макете страницы и отдельно не совпадают

**Comment by yndx-shri-reviewer** [comment]
Обновили и макет страницы. Спасибо
