### ISSUE TITLE
Значение ghost модификатора view в блоке text - опечатка?

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-1#46]
<img width="872" alt="task-1 2019-06-30 11-07-36" src="https://user-images.githubusercontent.com/1572715/60392123-48dd4000-9b27-11e9-9797-5b39e82d7bc3.png">

В теме не задано цвета ghost. Наверное здесь должно быть extra?

**Comment by NazarkinRoman** [comment]
+ в теме задается не `primary`, а `main` цвет

**Comment by yndx-shri-reviewer** [comment]
Так эти модификаторы называются в нашей дизайн-системе. Опечатки нет.
