### ISSUE TITLE
Блок payment. Опечатка в миксах?

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#47]
У Блока payment в элементе payment__header
указаны миксы form__item_space-v_l  и form__item_space-h_xl
То есть внутренние отступы по вертикали получается меньше, чем по горизонтали.
Но на скриншоте видно, что все наоборот.
Нет ли там опечатки?

**Comment by SkyFlame00** [comment]
Горизонтальные отступы должны быть такими (если попиксельно измерять, то все сходится). Но вот вертикальные отступы вообще странные - 32px снизу против 29px сверху. Мало того, что это ни разу не `form__item_space-v_l`, так они еще и не пропорциональные. Может, предполагается, что мы сами через стили зададим дополнительные отступы: я так и сделал, но у меня это вызывает вопросы.

Вот сейчас верстал блоки warning и product, так там та же картина - нужно дополнительно определять стили для отступов. Плюс у меня там еще вопрос по поводу того, как правильно делать отступы между строками текста. Существующие значения модификатора `type` не подходят (в блоке отступ между строками равен 12px), значения межстрочных интервалов, которые я тоже пока нигде не использовал, тоже не подходят.

**Comment by NazarkinRoman** [comment]
+1, тоже не понятно как там достичь pixel perfect. хотелось бы услышать окончательный ответ.

**Comment by yndx-shri-reviewer** [comment]
Мы проверили. Опечатки в условии нет, скриншот также актуален.
