### ISSUE TITLE
Аккордеон в блоке history

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#48]
В блоке `history` используются элементы блока `e-accordion`: `e-accordion__short` и `e-accordion__more`. Но нигде здесь не используется сам блок `e-accordion`. Вопрос: можно ли примиксовать `e-accordion` к одному из блоков блока `history`, если логика моего скрипта того требует? Просто мне кажется логичным, что элементы аккордеона должны быть вложены в сам аккордеон, а не располагаться произвольным образом на странице.

**Comment by yndx-shri-reviewer** [comment]
Да, конечно. Примиксуйте его к history__transaction, т.к. он является их общим контейнером. Мы добавим этот микс в описание.

**Comment by Astarta0** [comment]
> Да. Примиксуйте его к history__transaction, т.к. он является их общим контейнером.
Обновите, пожалуйста, спецификацию к history - блоку, чтобы потом были доказательства, если что )

От себя добавлю - логичнее все-таки к history миксовать, аккордеон же один, накидывается на весь блок.  Но это лично мое предпочтение)

**Comment by SkyFlame00** [comment]
**Astarta0**, так нет, `history` это же весь блок, т.е. список. `history__transaction` - элемент списка, поэтому на него накидывать

**Comment by SkyFlame00** [comment]
**yndx-shri-reviewer**, допустимо же такое, что клик для раскрытия `history__hide` приходится только по `history__show`? Я веду к тому, что если пользователь кликнет по внутренним отступам history__transaction, которые, конечно, не являются частью `history__show`, то `history__hide` не покажется, хотя пользователь будет ожидать этого. [Вот иллюстрация](https://ibb.co/vxjN4Y7) (по зеленой зоне будет приходится клик пользователя, и этот клик не будет обработан, то есть `history__hide` не откроется). Если это важно, решением могло бы быть создание внутренних отступов отдельно для `history__hide` и `history__show`.

**Comment by Astarta0** [comment]
> **Astarta0**, так нет, `history` это же весь блок, т.е. список. `history__transaction` - элемент списка, поэтому на него накидывать

Да я понимаю. Просто в моем понимании аккордеона это должно выглядеть так, что
1. Аккордеонов на странице может быть несколько
2. Аккордеон - интерактивный блок без визуального в нашем случае представления
3. Накидывается на блок для придания интерактивности
4. Содержит item'ы: 
- при взаимодействии с одним блоком аккордеона, дргие не должны никак реагировать
- при взаимодействии с блоком, раскрытый айтем аккордиона может быть только один, т.е. все остальные должны скрываться

**Comment by SkyFlame00** [comment]
**Astarta0**, понял, но тогда нужен элемент **e-accordion__item**, но он не прописан. Видимо предполагается, что раскрытыми могут быть сразу все. **yndx-shri-reviewer**, это так?

**Comment by yndx-shri-reviewer** [comment]
@SkyFlame00, раскрытыми могут быть и сразу все, и ни один.
Что касается кликабельной области, то вы можете сделать кликабельной только область внутри history__show.

@Astarta0, с точки зрения БЭМ в условии ошибки нет. БЭМ допускает примиксовывание отдельных элементов блока. Вопрос изначально был в том, допустимо ли примиксовать блок e-accordion и куда. Тем не менее этот микс не является обязательным.
