### ISSUE TITLE
Блок articles

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#51]
В блоке articles есть элемент articles__pic, на который миксуется тема theme_color_project-inverse, в этой теме задан бордерный цвет равный #fff, в результате этого блок image должен был быть с белой границей, но на [скриншоте](https://raw.githubusercontent.com/yndx-shri-reviewer/task-1/master/assets/screenshots/articles.png) то ли границы вобще нет, то ли цвет границы черный.

**Comment by yndx-shri-reviewer** [comment]
Тема просто задает цвет границы, но не определяет ее наличие или отсутствие.

**Comment by shishkinilya** [comment]
Да, но блок image по описанию имеет границу

> image
Блок служит для отображения изображений. Растягивается на всю ширину, имеет границу и содержит з

**Comment by SkyFlame00** [comment]
Цвет границы точно черный, потому что картинка имеет нифига не инверсную тему, а дефолтную. В задании постоянно путаница между дефолтной и инверсной темой (открытые на эту темы issues так и остались нерешенными). Насколько я понимаю, инверсная тема [должна выглядеть так](https://github.com/yndx-shri-reviewer/task-1/blob/master/assets/screenshots/product2.png?raw=true).

**yndx-shri-reviewer**, скажите, что в задании ошибка, и на деле у картинки не должен стоять модификатор на инверсную тему?

**Comment by yndx-shri-reviewer** [comment]
В подсказках к блоку articles у элемента articles__pic явно указано, что к нему примиксована инверсная тема.

**Comment by yndx-shri-reviewer** [comment]
Мы обновили описание блока image и контентных блоков, в которых используется блок image.
В дефолтной теме изображение имеет черную заглушку, черную границу и белый фон. В инверсном - белую заглушку и границу и черный фон.
Задаются эти параметры темой и при необходимости переопределяются на уровне контентного блока.
