### ISSUE TITLE
Блок product - элемент image

### ISSUE THREAD

**Issue by vaiil** [yndx-shri-reviewer/task-1#52]
https://github.com/yndx-shri-reviewer/task-1/blob/master/CONTENT.md#%D1%81%D0%BC%D1%8B%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA-product

Вот здесь в описании image встречается дважды:
1. Элементы без примиксованных блоков паттернов
2. Вложенные контентные блоки

Из первого следует, что необходимо создать product__image, это верно?
И в таком случае на него же миксить блок image или он должен быть вложен в product__image?

**Comment by SkyFlame00** [comment]
Думаю, нужно просто использовать блок `image` (он просто фигурирует в двух местах сразу). Если бы нужно было создать `product__image`, это было бы написано явно.

**Comment by yndx-shri-reviewer** [comment]
Поправили описание. Там необходимо использовать блок image, примиксовав к нему элемент product__image.

**Comment by vaiil** [comment]
@yndx-shri-reviewer в блоке commercial та же ситуация.

**Comment by yndx-shri-reviewer** [comment]
И там поправили. Спасибо
