### ISSUE TITLE
Блоки COVER и COMMERCIAL - правая внутренняя граница

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-1#53]
На предоставленных скриншотах можно заметить, что правый отступ на 1px меньше вертикальных и левого. Отсюда вопрос - корректно ли сделаны скриншоты этих блоков? Могло быть так, что, например, 1 пиксель справа случайно обрезался?

**Comment by yndx-shri-reviewer** [comment]
Да, такое возможно. Хром иногда может "съесть" лишний пиксель при создании скриншота элемента.
