### ISSUE TITLE
Опечатка в названии блока subscription

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-1#54]
Нашел опечатку в названии элементов блока `subscription`. Слово написано через букву "b". Могут возникнуть ошибки при проверке заданий.

<img width="558" alt="task-1 2019-07-02 23-15-19" src="https://user-images.githubusercontent.com/1572715/60528745-5b21ce80-9d1f-11e9-8dd4-fef1180c4b43.png">

**Comment by AlexandraSmirnova** [comment]
+1 поправьте пожалуйста везде, где опечатка

**Comment by philipusis** [comment]
Поправим и сделаем на всякий случай автозамену в коде на этапе сборки на случай, если кто-то не обратит на это внимания.

**Comment by danilstoyanov** [comment]
> Поправим и сделаем на всякий случай автозамену в коде на этапе сборки на всякий случай.

Здравствуйте :)
Вчера обещали выкатить более подробные описания крашей для автотестов страниц. Сегодня получится это сделать?

**Comment by philipusis** [comment]
> > Поправим и сделаем на всякий случай автозамену в коде на этапе сборки на всякий случай.
> 
> Здравствуйте :)
> Вчера обещали выкатить более подробные описания крашей для автотестов страниц. Сегодня получится это сделать?

Да. У нас уже выкачено сохранение скриншотов. Они будут сохраняться каждый раз в новой ветке в папке screenshots.
Ошибки консольные появятся в интерфейсе вечером.

**Comment by chrstnv** [comment]
> > > Поправим и сделаем на всякий случай автозамену в коде на этапе сборки на всякий случай.
> > 
> > 
> > Здравствуйте :)
> > Вчера обещали выкатить более подробные описания крашей для автотестов страниц. Сегодня получится это сделать?
> 
> Да. У нас уже выкачено сохранение скриншотов. Они будут сохраняться каждый раз в новой ветке в папке screenshots.
> Ошибки консольные появятся в интерфейсе вечером.

Подскажите, пожалуйста, уже можно искать ветку с сохраненными скриншотами? Она будет в этом репозитории? Если она не появляется, это означает, что есть ошибки в функции шаблонизации?

**Comment by philipusis** [comment]
Да. Ветки создаются в вашем же репозитории. Если они не появляются, значит, ошибки в функции шаблонизации.

**Comment by chrstnv** [comment]
> Да. Ветки создаются в вашем же репозитории. Если они не появляются, значит, ошибки в функции шаблонизации.

Спасибо большое! Тогда буду ждать логи :)
