### ISSUE TITLE
Формат модуля функции шаблонизации

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#55]
В описании к фукции шаблонизации указан экспорт функции в формате `esm`.
```
/**
* @param  {object} obj — Структура блоков интерфейса в формате BEMJSON
* @return {string} HTML разметка страницы
*/
export default function (obj) {
   // ...
}
```
Она должна экспортирована именно так или также должна иметь поддержку `commonjs` модулей?

**Comment by yndx-shri-reviewer** [comment]
Это не принципиально. Перед выполнением тестов мы собираем готовый бандл webpack'ом, который поддерживает и тот, и другой синтаксис.
