### ISSUE TITLE
Идентификация типа фона и текста

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#56]
В этой `issue` https://github.com/yndx-shri-reviewer/task-1/issues/17 тема поднималась, но не получила должного расскрытия.

При описании базовых блоков было указано, что фоны блоков интерфейса подразделяются на 3 типа:
1. `дефолтный`
2. `акцентный`
3. `бордерный`

**Мне понятно:**
1. как это реализовать (подсказки не нужны)
2. что это просто термины из типографики и что они нужны для описания.

**Мне не понятно:**
1. По каким критериям можно определить к какому именно типу фона относится блок? Например:
    1.1. в описании про акцентый цвет фона говорится, только в контексте контроллов. Значит ли что акцентными блоками можно считать только контролы?
    1.2. не нашел прямого упоминания `бордерного` цвета фона. Бордерный фон - это фон, который нужно использовать когда у **любого (?)** блока есть рамка или это цвет рамки?
    1.3. К каким блокам может применятся дефолтный фон? Ко всем блокам, но не элементам?
2. Что можно считать контроллом?
    2.1. в описании увидел, что `.input` является контроллом в `issue` увидел еще `.button`. Это все базовые блоки, которые являются контроллами?
   2.2. Являются ли контроллами какие-либо контентные блоки? Например `.onoffswitch` кажется контроллом.

**Comment by yndx-shri-reviewer** [comment]
1.1 Контролы и прогресс
1.2 Всё верно, это цвет рамки
1.3 Как правило достаточно указать только цвет фона самого блока. У элементов имеет смысл его указывать только в том случае, если на область элемента набрасывается другая цветовая Тема.

2.1 Под контролами подразумеваются самостоятельные переиспользуемые сущности при помощи которых осуществляется управление интерфейсом (кнопки и инпуты)
2.2 Да, onoffswitch тоже можно считать контролом.
