### ISSUE TITLE
Контентные блоки в функции-шаблонизаторе

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-1#57]
Например, имеем следующий bemjson на входе:
```
{block: 'payment'}
```
Должна ли функция-шаблонизатор сгенерировать полную верстку блока payment со всеми вложенными элементами или на вход будет подаваться полноценный bemjson с описанием всех внутренних элементов?

**Comment by yndx-shri-reviewer** [comment]
Мы будем подавать полный bemjson с описанием всех внутренних элементов.
