### ISSUE TITLE
Блок subscription

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#58]
Прошу проверить описание блока Subscription

![3a7b0f40ce](https://user-images.githubusercontent.com/20458127/60655775-01242480-9e57-11e9-8aa7-22ad3b4964d0.jpg)

Не является ли лишним микс `list__item_space-b_s` на элементе `subscription__control`?
Во-первых из этого следует что эта нода должена лежать внутри элемента `subscription__advantages`, т.к. только на него миксуется блок `list`.
Во-вторых:

![1b58b8298b](https://user-images.githubusercontent.com/20458127/60657027-434e6580-9e59-11e9-8827-73a915b52c1f.jpg)

из описания следует что отступ в футере между инпутом и кнопкой должен быть добавлен в исходные стили, как итог получается внутренний отсутп от микса `list__item_space-b_s` + внешний отступ из исходных стилей.

**Comment by SkyFlame00** [comment]
1) `footer` сам имеет микс `list`, то есть он является списком, а контролы - элементы списка
2) Мне показалось, что `list__item_space-b_s` это и есть "_отступ между блоками input и button..._", хотя замечание, вообще, верное

**Comment by shishkinilya** [comment]
Спасибо, да, футер я проглядел, но в любом случае непонятно каким образом реализовать отступ между инпутом и кнопкой: добавлением margin к элементу `.subscription__control` или миксом `.list__item_space-b_s`

**Comment by SkyFlame00** [comment]
Собственно, дополнительный вопрос появился. Почти тот же, что и у **shishkinilya**: в четвертом пункте исходных стилей требуется задать внешний отступ `s` у строк, однако у `subscription__advantage` уже есть такой отступ, правда внутренний (`list__item_space-b_s`).

**Comment by yndx-shri-reviewer** [comment]
Спасибо за замечание. Поскольку отступ должен быть внешний, то на subscription__control должен миксоваться list__item_indent-b_s. Поправили в условии.
