### ISSUE TITLE
Отступы в product.html и отступы в сетке

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#59]
1) На странице product.html после первой секции предполагается нижний отступ снизу размером xxxxl (48px). Однако внутри этой секции в конце есть параграф, который снизу делает отступ в 21px. Предполагается, что отступ секции "съест" отступ параграфа и в итоге разница между секциями станет равна 53px (48px + нижний отступ word, который не съедается). У меня это не так, и реальный отступ составляет 74px. Это происходит потому, секции используют grid, а он у меня построен на флексбоксах. И внешние отступы элементов сетки интерпретируются как "внутренние" отступы, поэтому условно итоговый отступ складывается из отступов word (5px), параграфа (21px) и внешнего отступа секции (48px). А должен складываться из word и отступа секции. 
![product1](https://user-images.githubusercontent.com/7037108/60744713-e26d7d00-9f7f-11e9-84f1-7f7d72e30d93.png)

**Вопрос**: что в таком случае делать? Делать не на флексбоксах, которые как мне кажется очень здесь подходят, и использовать блочные элементы? Или можно вручную в стили страницы добавить стиль, отменяющий нижний отступ у параграфа?

2) Допускается ли возможность расхождения расположения элементов в несколько пикселей в сетке? Я думаю, логика работы моей сетки верна, однако в некоторых местах имеются расхождения в 2-3 пикселя. Например, здесь (вопрос про расхождение по вертикали в блоке history в другой issue):
![index1](https://user-images.githubusercontent.com/7037108/60745483-15fdd680-9f83-11e9-8372-bb696f592f79.png)

Однако ситуация намного хуже в product.html. Здесь левая секция меньше на 3px, чем предполагается заданием, а правая, соответственно, больше на 3px. Это смещение в 3px приводит к тому, что слова перемещаются на следующую строку. Если на эти пресловутые 3px увеличить левую секцию, то все встанет как надо.
![product2](https://user-images.githubusercontent.com/7037108/60745426-cd461d80-9f82-11e9-9d8d-da0193444655.png)

**Вопрос**: ОК ли такие расхождения? (автотесты еще не пытался проходить)

**Comment by shishkinilya** [comment]
1ый вопрос плюсую, тоже непонятно как так, такое ощущение что на скринах последнему текстовому блоку в первой секции не добавили микс text_type_p

**Comment by yndx-shri-reviewer** [comment]
@shishkinilya если модификатор text_type не указан явно, то его задавать не нужно. Для абзацев на странице product он не задается.

@SkyFlame00 если из-за этого происходит перенос слов, то скорее всего, автотесты провалятся на этой странице. Небольшие расхождения в сетке могут вам дать большую разницу в масштабе всей страницы.
