### ISSUE TITLE
Название модификатора блока theme

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#6]
В задании реализации контентых блоков: на блоки events, articles и collect миксуется модификатор `theme_color_whitepaper-inverse`, судя по таблице с модификаторами блока `theme`, название модификатора должно быть `theme_color_project-inverse`

**Comment by yndx-shri-reviewer** [comment]
Была опечатка в значении модификатора темы, следует использовать `theme_color_project-inverse`
