### ISSUE TITLE
Поля в упрощенном формате bemjson

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#60]
Не могу пройти ни один автотест в первом задании. Пытаюсь выяснить все причины.

Достаточно ли следующих полей для bemjson или вы скармливаете функции-шаблонизатору еще какие-то другие?

block: String
elem: String,
content: Object | Object[]
mix: Object[]
mods: Object,
elemMods: Object

**Comment by SkyFlame00** [comment]
Тут меня немного осенило, что параметры конкретным блокам я передаю, наверное, неправильным образом. Их нужно задавать при помощи поля js, чтобы они затем хранились в data-bem и считывались функцией-шаблонизатором?

**Comment by danilstoyanov** [comment]
Тоже не могу пройти ни одного автотеста в первом задании :)
Локально функция-шаблонизатор выполняет поставленные задачи.
Сижу и гадаю, в чём же может быть проблема. А скоуп потенциальных проблем достаточно широк. То что в голову приходит:
1)  Ошибка в фукнции шаблонизаторе
--- Неверная обработка входных данных
--- Неверная генерация классов
--- Проблемы при обходе bemjson дерева
2) Ошибка в файле script.js
--- Некорректно работает переключатель темы
--- Некорректно работает аккордион
3) Ошибки в файле стилей
--- Несовпадение стилизированной разметки с эталонными скриншотами

Было бы здорово, если бы люди, успешно прошедшие автотесты, отписали в этот issue, что всё работает как нужно и ошибки всё-таки где-то на нашей стороне кроются.

**Comment by danilstoyanov** [comment]
Ну и было бы удобно для поступающих, чтобы разработчики заданий не поскупились на чуть более подробное описание краш-репортов.

![image](https://user-images.githubusercontent.com/18240896/60755168-58abc700-9ff4-11e9-9cff-8d975249e106.png)

Такое описание скудновато на мой личный взгляд.

**Comment by SkyFlame00** [comment]
**danilstoyanov**, вот-вот и у меня моя функция все как нужно делает, и итоговые страницы почти что такие, как на скриншотах. "Почти что" потому, что есть вопросы насчет верстки, которые пока не были отвечены в предыдущих issues. И все эти вопросы относительно отступов (ручками эти отступы переопределять и доопределять тогда, что ли?).

Да, насчет описания краш-репортов согласен.

Впереди еще два больших задания, к которым я не приступал, а время уже, можно сказать, на исходе, учитывая сколько пришлось потратить на скрупулезное выполнение первого.

**Comment by NazarkinRoman** [comment]
Поддерживаю. Думаю, также полезно было бы иметь какое-то понимание о том, как запускается функция-шаблонизатор внутри тестовой среды и какие расхождения с эталонными скриншотами воспринимаются как допустимые.

**Comment by UnicornShade** [comment]
Всю неделю потратил на попытки пройти тесты. Перепробовал десятки различных комбинаций стилей и верстки, локально главная страница сходится с макетом идеально. Шаблонизатор собирает верстку правильно (по крайней мере визуально), непонятно почему тесты не проходят.

Поддерживаю, что нужно больше информации в репортах.
Также помнится, что в видео говорили о возможности выложить реализацию json. Это дало бы представление в каком месте могут быть расхождения.

**Comment by kaban270790** [comment]
Плюсую. Тоже не могу первое задание пройти, ни один тест не подтверждается. Когда пару раз не прошел тесты, решил хоть индекс-десктоп подогнать, для проверки, но ни в какую, уже 1в1 пиксель вогнал, но ни в какую

**Comment by shishkinilya** [comment]
Страница content (только она собралась идеально), пиксель в пиксель, тест этой страницы все равно не проходит, у всех также?
![localhost_63342_task-1_content html__ijt=n23kcpuml3odgdseks5sih7acp](https://user-images.githubusercontent.com/20458127/60878094-c26fdf00-a247-11e9-84a7-6707b0326519.png)

**Comment by SkyFlame00** [comment]
> Страница content (только она собралась идеально), пиксель в пиксель, тест этой страницы все равно не проходит, у всех также?
> ![localhost_63342_task-1_content html__ijt=n23kcpuml3odgdseks5sih7acp](https://user-images.githubusercontent.com/20458127/60878094-c26fdf00-a247-11e9-84a7-6707b0326519.png)

Ни одна страница не проходит

**Comment by yndx-shri-reviewer** [comment]
Мы разбираемся с этим issue, чтобы исключить ошибку на нашей стороне, и дадим комментарии по нему не позднее завтрашнего дня.

**Comment by yndx-shri-reviewer** [comment]
В ближайшее дни добавим отображение дополнительной информации о результатах тестов включая логи ошибок из консоли браузера.
Также добавим вывод разницы между вашей версткой и эталоном в виде отдельного изображения.

**Comment by yndx-shri-reviewer** [comment]
@SkyFlame00, @danilstoyanov, @UnicornShade, @shishkinilya у вас падает шаблонизатор на этапе выполнения.

При запуске тестов мы скачиваем вашу функцию шаблонизации, импортируем ее в наш клиентский код, собираем webpack'ом бандл, отдаем его клиенту и на клиенте выполняем шаблонизацию.
Поэтому проверьте, пожалуйста, что вашу функцию можно успешно импортировать, собрать в бандл и запустить на стороне клиента.

**Comment by yndx-shri-reviewer** [comment]
@NazarkinRoman у вас не прошли тесты, т.к. есть расхождения в верстке.
![index_1920](https://user-images.githubusercontent.com/50715001/60982349-a1d78000-a340-11e9-9e37-fe3e16e660fb.png)
![product_1920](https://user-images.githubusercontent.com/50715001/60982352-a1d78000-a340-11e9-979a-b7578d63adbb.png)

**Comment by kaban270790** [comment]
@yndx-shri-reviewer А у меня почему не проходит index страница?

**Comment by yndx-shri-reviewer** [comment]
> @yndx-shri-reviewer А у меня почему не проходит index страница?

Аналогично: ошибки в функции шаблонизации. Скоро добавим вывод логов, и вы сможете посмотреть на логи ошибок.
