### ISSUE TITLE
Отступ в блоке event

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#61]
Между картинками и заголовком отступ равен 37px. Он складывается из отступа `xl` (третий пункт исходных стилей), который равен 24px, а также верхнего отступа слов, который, по всей видимости, здесь равен 13px: 37px = 24px + 13px. Однако по моим расчетами слово размера `xxl` должно иметь такие отступы: `margin: 9px 0 12px` (это может быть подсказкой другим участникам, хотя маловероятно). И такой отступ для слова размера `xxl` работает везде. То есть у меня имеется расхождение в 4px, поскольку по моим расчетам у слова должен быть отступ в 9px, а не в 13px.
![1](https://user-images.githubusercontent.com/7037108/60756434-dc21e400-a005-11e9-8b52-330cd5e40b41.png)
![event](https://user-images.githubusercontent.com/7037108/60756514-e0023600-a006-11e9-9bbb-7d377c7cb775.png)

**Вопрос**: нет ли здесь ошибки? Или можно искусственно задать дополнительно этот отступ в 4px в стилях?

**P.S.** (!!!)
Вообще, несовпадение отступов у слов у меня есть только в блоке event и в блоке history. Но блок history это вообще отдельная песня: там, если следовать точно указаниям, вообще куча расхождений.

И отступы у слов - тоже странное дело. Обладая информацией о размере слов и размере межстрочного интервала, я сидел и экспериментально пытался вычислить у слова какого размера какие отступы. Хотя если под межстрочным интервалом подразумевается все же css'овский `line-height`, то слова должны располагаться ровно посередине, то есть отступы сверху и снизу должны быть одинаковы (или разница должна составлять только 1px), на деле же у некоторых слов разница в отступах составляет более 1px: как, например, у слова размером `xxl` разница между верхним и нижним аж 3px. Итак, если моя догадка верна, то межстрочный интервал = размер текста + отступы сверху и снизу. Тогда межстрочный для слова размером xxl определяется так: 9px (сверху) + 13px (размер слова) + 12px (снизу) = 34px. Для других размеров другие отступы.
![lineheight](https://user-images.githubusercontent.com/7037108/60756658-d8439100-a008-11e9-9c43-43c4e7ca426c.png)

Может я что-то упускаю? Возможно, что-то совсем базовое. Если так, подскажите, пожалуйста, я уже устал мучаться с этими отступами у слов.

**Comment by shishkinilya** [comment]
У меня ровно такая же ситуация, отступы у слов тоже высчитывал отдельно, для xxl у меня отступы такие же, кроме как написать такой комент в коде ничего не придумал, печально что некоторые issue так и остаются без ответа и выкручивайся как хочешь
![0ca9db1308](https://user-images.githubusercontent.com/20458127/60759898-1656aa00-a035-11e9-9e86-2753ade255a4.jpg)

**Comment by chrstnv** [comment]
У меня точно такая же проблема. Тоже решила путем магического хака. В остальных местах отступы в текстах сходятся точно, а именно в этом — нет.

**Comment by yndx-shri-reviewer** [comment]
Обновили скриншоты в соответствии с условием. Проверьте, пожалуйста.

>Хотя если под межстрочным интервалом подразумевается все же css'овский `line-height`, то слова должны располагаться ровно посередине, то есть отступы сверху и снизу должны быть одинаковы (или разница должна составлять только 1px)

А на основании чего вы так считаете?

**Comment by neuspeed** [comment]
Подскажите, пожалуйста. А в условии нет ошибки насчет:
 - величина отступа между заголовком и текстом — s;
Судя по скриншоту, отступ от заголовка до описания такой же как и между логотипами и заголовкам, т.е. xl

**Comment by SkyFlame00** [comment]
> Обновили скриншоты в соответствии с условием. Проверьте, пожалуйста.
> 
> > Хотя если под межстрочным интервалом подразумевается все же css'овский `line-height`, то слова должны располагаться ровно посередине, то есть отступы сверху и снизу должны быть одинаковы (или разница должна составлять только 1px)
> 
> А на основании чего вы так считаете? У вас же там не текст, а блоки.

Ну так text__word имитируют поведение обычного текста. Так а на основании чего рассчитывать отступы у слов? Логику работы межстрочного интервала у обычного текста можно было бы применить и к text__word, но как бы не так, ведь отступы у блоков не пропорциональные.

@chrstnv у вас и в history__show отступы у слов совпадают?

**Comment by yndx-shri-reviewer** [comment]
>   Судя по скриншоту, отступ от заголовка до описания такой же как и между логотипами и заголовкам, т.е. xl

Проверили. Ошибки нет.
