### ISSUE TITLE
Блок history. Элементы текста справа.

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#62]
Поясните, пожалуйста, про текстовые элементы справа в блоке history. Понятно, что это text с вложенным text__word, но вот во что вложен блок text? 
![history](https://user-images.githubusercontent.com/9385858/60770790-8a518a80-a0e7-11e9-9f0e-fcc804cc523e.PNG)
Если с нижним элементом можно догадаться, что он относится к history__actions, то где верхний элемент обитает совсем не понятно.
![Снимок_LI](https://user-images.githubusercontent.com/9385858/60770812-c4bb2780-a0e7-11e9-9f5a-c4be2321706a.jpg)

**Comment by danilstoyanov** [comment]
Хм, не знаю насколько я правильно понял спецификацию, когда верстал данный блок, но у меня получилось так:
![history](https://user-images.githubusercontent.com/18240896/60773064-2ab7a700-a108-11e9-97c2-0c0e13bcee9a.png)

**Comment by yndx-shri-reviewer** [comment]
> Поясните, пожалуйста, про текстовые элементы справа в блоке history. Понятно, что это text с вложенным text__word, но вот во что вложен блок text?
> ![history](https://user-images.githubusercontent.com/9385858/60770790-8a518a80-a0e7-11e9-9f0e-fcc804cc523e.PNG)
> Если с нижним элементом можно догадаться, что он относится к history__actions, то где верхний элемент обитает совсем не понятно.
> ![Снимок_LI](https://user-images.githubusercontent.com/9385858/60770812-c4bb2780-a0e7-11e9-9f5a-c4be2321706a.jpg)

В нижние два текста в развернутом виде вложены в history__actions.
Верхний обведенный text - в history__quantity.

**Comment by vaiil** [comment]
@yndx-shri-reviewer В документации нет блока history__quantity, добавьте его пожалуйста.
