### ISSUE TITLE
Блок Section

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#63]
Если я правильно понимаю, то это блок section, но в задании никак не описано что он должен иметь background.
 
![2](https://user-images.githubusercontent.com/20458127/60808704-9bef6c80-a191-11e9-9030-e0d01162b08b.jpg)

**Comment by icwet** [comment]
Я так понимаю это просто внутренний блок темы внутри другой темы. Определяющий свои правила конкретно для этой секции.

**Comment by yndx-shri-reviewer** [comment]
Вы можете задать ему background, если считаете нужным. В задании на этот счет нет никаких ограничений.
