### ISSUE TITLE
Блок Payment

### ISSUE THREAD

**Issue by neuspeed** [yndx-shri-reviewer/task-1#66]
Подскажите, пожалуйста, в блоке Payment есть внутренние компоненты с границами, а согласно макету дизайн-системы я их не вижу и могу только предположить, что это элементы form__item, но с границами, хотя таких модификаторов у них нет. Границы добавлять в таком случае через переопределение или все-таки будет модификатор на границы? Допускаю, что я вообще неверно трактую этот блок.
![payment mark](https://user-images.githubusercontent.com/5637282/60953901-bc8d0300-a306-11e9-8c6e-8f2da96360e9.png)

**Comment by yndx-shri-reviewer** [comment]
Спасибо за вопрос. Там вложенный контентный блок input с модификатором input_size_l. Добавили в описание блока.
