### ISSUE TITLE
Блок Warning

### ISSUE THREAD

**Issue by neuspeed** [yndx-shri-reviewer/task-1#67]
В описании блока Warning, а именно в спецификации на вложенные контентные блоки, для placeholder указано значения для модификатора view - placeholder_view_primary. В описании блока placeholder такого модификатора нет. Подскажите как с ним быть.

UPD: То же касается informer_view_default.

**Comment by yndx-shri-reviewer** [comment]
Они задают цвет фона блоков. Добавили в описание. Спасибо
