### ISSUE TITLE
Тема у блока warning

### ISSUE THREAD

**Issue by quadratos** [yndx-shri-reviewer/task-1#68]
На скриншоте страницы блок warning выглядит так, как если к нему примиксовать соответствующую тему, но в подсказке о блоке theme ничего нет, только "warning (informer_view_default informer_border_all)". Значит ли это, что при проверке блок theme так же не будет примиксован и все цвета надо дописать к блоку warning руками?

**Comment by yndx-shri-reviewer** [comment]
Дописывать самостоятельно ничего не нужно. Это делается миксом соответствующей темы. Добавили в подсказку микс theme_color_project-warning.
