### ISSUE TITLE
History show - list__item_indent-t_m

### ISSUE THREAD

**Issue by vaiil** [yndx-shri-reviewer/task-1#69]
![Component](https://user-images.githubusercontent.com/3755615/61131694-8a280500-a4c2-11e9-8945-456d2ef58552.png)

У блока history show указан микс - list__item_indent-t_m, но не ясно где здесь должен быть отступ сверху в 16px. 
Красным выделен внутренний отступ в 20px history__transaction (он возникает из-за list__item_space-a_l).

**Comment by yndx-shri-reviewer** [comment]
Как уже говорилось в [этом issue](https://github.com/yndx-shri-reviewer/task-1/issues/20), здесь нет ошибки ни в условии, ни в макете.
Вам необходимо реализовать стили блока list таким образом, чтобы они, будучи примиксованными к элементам history, отображались, как указано в макете.

**Comment by vaiil** [comment]
В том issue вы говорите, что стили list не нужно переопределять. 
В описании блока list сказано, что space-a_l - внутренний отступ (то есть padding). 
Также сказано, что history__show - это вся видимая строка (то есть включая brand-logo). 

Тогда вопрос, каким образом можно добиться отступа в 20px brand-logo от верхнего border-а, при условии что у нас есть 20px padding и 16px margin (которые не могут друг на друга наложиться, а будут только суммироваться) без переопределения стилей list?

**Comment by WIVSW** [comment]
> В том issue вы говорите, что стили list не нужно переопределять.
> В описании блока list сказано, что space-a_l - внутренний отступ (то есть padding).
> Также сказано, что history__show - это вся видимая строка (то есть включая brand-logo).
> 
> Тогда вопрос, каким образом можно добиться отступа в 20px brand-logo от верхнего border-а, при условии что у нас есть 20px padding и 16px margin (которые не могут друг на друга наложиться, а будут только суммироваться) без переопределения стилей list?

Если элемент `.icon-plus__icon` будет абсолютно спозионированным относительно текста проблема пропадет.
