### ISSUE TITLE
разрешены ли фреймворки?

### ISSUE THREAD

**Issue by Youfka** [yndx-shri-reviewer/task-1#7]
Подскажите, можно ли использовать в задании фреймворки/библиотеки или нужно написать всё с нуля на чистом JS?

**Comment by dima117** [comment]
Можно использовать любые библиотеки и инструменты, но мы хотели бы увидеть для каждого небольшое описание, почему он необходим в проекте и почему выбрали именно его среди альтернатив.

**Comment by danilstoyanov** [comment]
> Можно использовать любые библиотеки и инструменты, но мы хотели бы увидеть для каждого небольшое описание, почему он необходим в проекте и почему выбрали именно его среди альтернатив.

https://www.npmjs.com/package/bem-json-to-html
Такие решения это уже слишком? Для реализации функции-шаблонизатора

**Comment by dima117** [comment]
Примите решение самостоятельно. Важно, чтобы была понятна причина решения и чтобы были выполнены условия задания. Также имейте в виду, что цель задания - показать ваши профессиональные навыки.
