### ISSUE TITLE
Блок event. Отступ между изображениями.

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#70]
У блока event есть изображения, между которыми есть отступ. Даже есть специальный блок event__speaker, в котором судя по всему и нужно прописать этот отступ. Но вот сам отступ нигде не указан. Конечно, можно догадаться что это отступ xs, но было бы здорово, если бы это было точно указано в документации.
![event_LI](https://user-images.githubusercontent.com/9385858/61158508-cc246b80-a501-11e9-94c7-622774f55656.jpg)
![event-1](https://user-images.githubusercontent.com/9385858/61158488-bc0c8c00-a501-11e9-860f-1b0fced1ca55.PNG)

**Comment by yndx-shri-reviewer** [comment]
Между ними отступ величиной xs. Дополнили описание. Спасибо
