### ISSUE TITLE
Header и Footer. Горизонтальные отступы

### ISSUE THREAD

**Issue by AlexandraSmirnova** [yndx-shri-reviewer/task-1#71]
В документации сказано, что это блоки имеют следующие отступы:

> имеет вертикальные отступы в значении xxxl вертикальный и --gap горизонтальный;

С вертикальным все просто, а вот читая рядом про горизонтальный  я понимаю, что это соответствующий отступ по горизонтали, а не отступ, скажем между элементами. На скриншотах к header и footer мы видим горизонтальные отступы, только от layout (logo прилипает к границе layout и никаких доп. отступов по горизонтали не имеет)

В другом ишью по поводу этих отступов вы написали:

> Горизонтальные отступы будут проявляться в мобильном отображении, и это нормально.

В документации к о переменной gap видим:
![gap](https://user-images.githubusercontent.com/9385858/61170606-586f7680-a574-11e9-9e60-fb9801f4b7f9.PNG)

Получается, на десктопе у этой переменной не нулевое значение. Куда тогда должны деться 40px, если просто указать переменную gap в отступах?
Если горизонтальные отступы должны сбрасываться на десктопе и проявляться ТОЛЬКО в мобильном отображении, укажите это, пожалуйста, в документации.

**Comment by yndx-shri-reviewer** [comment]
Максимальная ширина контента внутри блоков - 1144px. Добавили это в описание и для header. Спасибо
