### ISSUE TITLE
Дополнительная информация по автотестам

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#73]
Добрый день :)

Недавно, в одном из ответов на [issue](https://github.com/yndx-shri-reviewer/task-1/issues/60), проверяющий сказал что для первого задания будет предоставлено более подробное описание ошибок (логи из консоли и возможно скриншоты с несовпадающими компонентами).
![image](https://user-images.githubusercontent.com/18240896/61205259-3b63b080-a6f8-11e9-9274-98e51e9013fb.png)

Интересно было бы узнать, когда планируются эти обновления, чтобы успеть доделать задания (для выполнения осталось 7 дней).

**Comment by yndx-shri-reviewer** [comment]
Не позднее завтрашнего дня уже будут выкачены.

**Comment by danilstoyanov** [comment]
> Добрый день! Не позднее завтрашнего дня уже будут выкачены.

Понял, спасибо!
