### ISSUE TITLE
Задайте вектор по написанию ф-ии шаблонизаци

### ISSUE THREAD

**Issue by Ren4ik336** [yndx-shri-reviewer/task-1#74]
Добрый день. Задайте пожалуйста вектор по написанию ф-ии шаблонизации.
Для начала, что я сделал. Проект решил сделать bem - стеке. За основу взял project-stub. С помощью bem create  создал нбх-е блоки дизайн-системы, написал стили для них. Написал bemjson страниц. С помощью сборщика ENB собрал файл стилей. Страницы запускаются на localhost:8080. Теперь пытаюсь пройти автотесты и в данный момент изучил инструкцию export для экспорта функций.
На вход шаблонизатора bem-xjst подал входные данные в формате bemjson и не добавляя шаблонов получил строку html соответственно, строка валидна и соответствует методологии bem. В настоящий момент не получается заэкспротить все это на автотест.
Дайте пожалуйста "пинка" для задания вектора дальнейшего изучения. "Лопата есть, подскажите куда копать":)))
Спасибо за внимание.

**Comment by danilstoyanov** [comment]
Я думаю, пинок (а точнее понимание, из-за чего не запускается функция) появится, когда выложат апдейты по результатам тестирования первого задания  :)
https://github.com/yndx-shri-reviewer/task-1/issues/73

**Comment by Ren4ik336** [comment]
Есть успехи в этом направлении?

**Comment by danilstoyanov** [comment]
@Ren4ik336 нет, моё задание тоже примерно в таком же состоянии. Вроде есть готовая архитектура и стили компонентов, вроде и функция шаблонизации локально работает как ожидается, но при проверке функция падает :(

**Comment by Ren4ik336** [comment]
Будем надеяться, что вскоре появятся логи ошибок, чтобы можно было понимать куда идти дальше. Успехов тебе в тестовых!!!!

**Comment by yndx-shri-reviewer** [comment]
Логи ошибок появились, @Ren4ik336 они вам помогли?

**Comment by Ren4ik336** [comment]
@yndx-shri-reviewer, задача мною еще не решена. Логи ошибок появились и мне помогли, но слабые знания js не дают мне в полной мере раскрыть решение задачи. Получил скриншоты с [object, object]. Это я так понимаю что из-за того, что возвращается bemjson вместо валидной html разметки. С помощью bem-xjst шаблонизатора, из примера, я вывожу в консоль html строку. Как все это реализовать с exportom функции я еще не понял. (При экспорте получается ошибка require is note defined. Ошибка Reference error. Возможно она возникает от того что браузеры не понимают модули и для них var bemxjst при экспорте не существует). Поэтому ушел читать Кантора.))) Вообще идея дизайн системы мне понравилась буду дальше ее развивать.

**Comment by yndx-shri-reviewer** [comment]
Вы проделали большую работу, удачи вам в решении задания!

**Comment by Ren4ik336** [comment]
@yndx-shri-reviewer , спасибо!
