### ISSUE TITLE
Цвета картинок (блок image)

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#75]
1. В #23 вы написали:

> В дефолтной теме изображение имеет черную заглушку, черную границу и белый фон. В инверсном - белую заглушку и границу и черный фон

Но как видно из картинок и самой верстки, цвет фона и цвет границы не могут быть разными (если фон черный, то и граница черная; фон белый - граница белая).

2. В подправленном описании блока image:

> Изображения с темой project-default имеют заглушку черного цвета. Заглушка
> 
> Изображения с темами project-default и project-brand имеют заглушку белого цвета. Заглушка(инверсия)

Дважды повторяется project-default. Верно должно быть так: `Изображения с темами project-inverse и project-brand имеют заглушку белого цвета`?

3. Во все той же #23 вы написали:

> Как вы могли заметить, блокам с инверсной темой может соответствовать как белая, так и черная картинка.
> Ваша задача как раз и заключается в том, чтобы придумать способ правильного отображения этого блока.

Я правильно понимаю вашу логику, что project-inverse инвертирует задаваемые сверху (родительскими элементами) переменные? Если сверху была задана переменная `--bg-default` с черным цветом, то project-inverse инвертирует и задаст внутри себя переменную `--bg-default` с белым цветом, так что дочерние элементы project-inverse будут использовать уже белый цвет вместо черного.

Я к этому пришел из следующего наблюдения. Вы сказали, что дефолтная картинка - это та с белым фоном и черной заглушкой. Тогда если проанализировать страницу collect.html, получим следующее (на картинке)

![collect-page](https://user-images.githubusercontent.com/7037108/61232100-30c80c00-a736-11e9-9dca-5ed77f7e5c29.png)

Остается вопрос с блоком product. На странице [index.html](https://github.com/yndx-shri-reviewer/task-1/blob/master/assets/pages/index.png?raw=true) он имеет цвета project-inverse, однако к нему такой модификатор не применен.

Если ваше утверждение `Ваша задача как раз и заключается в том, чтобы придумать способ правильного отображения этого блока` - это вручную определить стили для каждого блока с картинкой, тогда мое предположение неверно. Но я просто не вижу, как по-другому можно интерпретировать эти слова.

Если мое предположение верно, то я не вижу, как это можно сделать при помощи CSS. Конечно, можно сделать это при помощи js, но по мне это все бессмысленно, гораздо легче каждому блоку накидывать тему.

**Comment by philipusis** [comment]
> Дважды повторяется project-default. Верно должно быть так: `Изображения с темами project-inverse и project-brand имеют заглушку белого цвета`?

Поправили. Спасибо

**Comment by philipusis** [comment]
Дополнили описание блока product. На элемент product__image навешивается тема, которая задает внешний вид изображения. Дополнили подсказку к блоку product.

> Но как видно из картинок и самой верстки, цвет фона и цвет границы не могут быть разными (если фон черный, то и граница черная; фон белый - граница белая).

У блока commercial синий фон и белые граница и изображение.

**Comment by SkyFlame00** [comment]
@philipusis недоглядел cover и commercial. Получается, никакие хитросплетения не нужны, раз вы указали `theme_color_project-inverse / theme_color_project-default` у product__image?

**Comment by philipusis** [comment]
Да. Тема на product__image должна навешиваться в зависимости от темы на всем блоке.
Задание внешнего вида изображения возможно реализовать и без явного навешивания темы, только стилями контентного блока. Поэтому, чтобы исключить такую неоднозначность, мы будем навешивать тему явно.

**Comment by SkyFlame00** [comment]
@philipusis на странице product.html тоже есть блоки product. На них навесить project-inverse?

**Comment by philipusis** [comment]
Т.е. навесить? Вы же делаете css и функцию шаблонизации.

**Comment by SkyFlame00** [comment]
@philipusis в index.html тема блоков product определяется указанием: `theme_color_project-inverse / theme_color_project-default`. На странице product.html тоже есть блоки product. Но для них нет указания, какую тему использовать. Поэтому я предположил, что к ним должна быть применена тема project-default, раз уже всем картинкам в контентных блоках тема задается теперь явно.

**Comment by philipusis** [comment]
> в index.html тема блоков product определяется указанием: `theme_color_project-inverse / theme_color_project-default`.

Мы поправили подсказку. Посмотрите, пожалуйста.
На элемент product__image будет навешиваться одна из указанных тем: project-default или project-inverse. При этом на сам блок может быть навешана совершенно любая тема. Например, project-brand, как это сделано в блоке commercial.

**Comment by SkyFlame00** [comment]
@philipusis А что изменилось? Не вижу
![pr](https://user-images.githubusercontent.com/7037108/61286124-e5ac0880-a7ca-11e9-8a71-c639ba14b373.png)

**Comment by philipusis** [comment]
![image](https://user-images.githubusercontent.com/20648948/61286424-7c78c500-a7cb-11e9-81c7-63daade4c3f0.png)

Мы убрали формулировку "в зависимости от темы блока".

**Comment by SkyFlame00** [comment]
@philipusis Понял
