### ISSUE TITLE
Мелкие несовпадения в сетке

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#76]
У меня есть различие в 1px между эталонными скриншотами и моей версткой, но это связано с особенностями отрисовки элементов на странице в зависимости от наличия дробных значений.

Например, в index.html у каждого продукта ширина равна 212.8px (5 продуктов + отступы между ними суммарно в 80px = 1144px). Конечно, поскольку пиксель неделим, браузер даст продукту ширину либо 212px, либо 213px.

![px1](https://user-images.githubusercontent.com/7037108/61236722-6292a000-a741-11e9-9498-f707da81198a.png)

В итоге получается такое:
![px2](https://user-images.githubusercontent.com/7037108/61236815-9a014c80-a741-11e9-93f7-6f39a172eded.png)

Автотесты же должны пропустить такую "погрешность"?

**Comment by philipusis** [comment]
Сложно сказать наверняка. Скорее всего, проблем возникнуть не должно.
Если тесты всё же не пройдут из-за этого, то вы увидите на скриншотах. Они будут пушиться каждый раз в новую ветку.

**Comment by SkyFlame00** [comment]
@philipusis спасибо! То есть все-таки скриншоты будут, хорошо
