### ISSUE TITLE
Еще раз насчет блока history

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#77]
1. Добавьте, пожалуйста, блок history__quantity, о котором вы сказали в #62, в описание
2. Вы уже много раз говорили, что никаких ошибок в описании к блоку history у вас нет и что все можно сверстать нормально согласно данным вами указаниям, ничего при это не переопределяя. Хорошо. Скажите, пожалуйста, на каком(-их) этапе(-ах) из приведенных ниже картинок я совершаю логическую ошибку(-и): неправильно вкладываю блоки, неправильно определяю стили у list, history и т.д. Не могу понять, в каком месте я слеп, уже много раз проверял.

**Первое: нераскрытый блок**

![history1](https://user-images.githubusercontent.com/7037108/61292558-3840f100-a7da-11e9-8d4e-caf2a3f18c6e.png)

**Второе: раскрытый блок**

![history2](https://user-images.githubusercontent.com/7037108/61292449-ded8c200-a7d9-11e9-9f37-50f5863d28fc.png)

**Третье: отступы у слов в блоке history__show**. 

![history3](https://user-images.githubusercontent.com/7037108/61292227-522e0400-a7d9-11e9-804c-e6c6a98428a6.png)

Насчет слов: мне кажется, вычисленные мной отступы у слов всех размеров верные, потому что они работают исключительно везде, кроме блока history.

**Comment by yndx-shri-reviewer** [comment]
1. Добавили. Спасибо
2. Мы не даем подсказок по выполнению задания. Ваша задача как раз и заключается в том, чтобы при заданной структуре блоков написать стили таким образом, чтобы полученная верстка соответствовала макетам.
