### ISSUE TITLE
Отличие структуры страницы index

### ISSUE THREAD

**Issue by kaban270790** [yndx-shri-reviewer/task-1#78]
Здравствуйте!

Структура этих страниц одинаковая при тестах? У меня отличается построение элементарных блоков header и footer. По файлу `index_desktop` смог понять структуру некоторых блоков, а уже на `index_1920` она отличается.
![image](https://user-images.githubusercontent.com/27147261/61313863-004ea380-a804-11e9-8120-27188da617c0.png)
index_desktop:
![image](https://user-images.githubusercontent.com/27147261/61313914-1ceadb80-a804-11e9-87ef-d7ff05605a9e.png)
index_1920:
![image](https://user-images.githubusercontent.com/27147261/61313951-2d9b5180-a804-11e9-8518-6217e5ba44e7.png)

**Comment by kaban270790** [comment]
И попробовал сравнить эталонный скрин с макетом из `index_1920`, они не совпадают. Стоит ли на этот файл обращать внимание?
![image](https://user-images.githubusercontent.com/27147261/61314250-ebbedb00-a804-11e9-8664-0419a3c3109c.png)

**Comment by SkyFlame00** [comment]
@kaban270790 куда скриншоты складываются? Писали, что должен быть форк, но у меня нет форков от своего приватного репозитория.

**Comment by yndx-shri-reviewer** [comment]
Файлы с цифрами в названии - это старые версии, игнорируйте их. Они попали в репозиторий по ошибке. Мы это поправили, и больше они сохраняться в репозиторий не будут.

**Comment by danilstoyanov** [comment]
> Файлы с цифрами в названии - это старые версии, игнорируйте их. Они попали в репозиторий по ошибке. Мы это поправили, и больше они сохраняться в репозиторий не будут.

Ещё бы логи завезти, и вообще было бы всё круто :3

**Comment by kaban270790** [comment]
> @kaban270790 куда скриншоты складываются? Писали, что должен быть форк, но у меня нет форков от своего приватного репозитория.

Как я понял, где-то тут уже давали ответ, если нет скриншотов, то ошибка в шаблонизаторе
Они в отдельных ветках на каждый тест с указанием времени теста

**Comment by kaban270790** [comment]
> Файлы с цифрами в названии - это старые версии, игнорируйте их. Они попали в репозиторий по ошибке. Мы это поправили, и больше они сохраняться в репозиторий не будут.

Понял, спасибо

**Comment by kaban270790** [comment]
@yndx-shri-reviewer А точно не нужно обращать внимания именно на файлы с цифрами? В частности файлов с цифрами как раз по кол-ву тестов, а без цифр только как будто скрины страницы `index`?
![image](https://user-images.githubusercontent.com/27147261/61319925-0434f280-a811-11e9-93de-0773f789ce20.png)

**Comment by SkyFlame00** [comment]
@yndx-shri-reviewer когда будет добавлена поддержка логов?

**Comment by kaban270790** [comment]
> @yndx-shri-reviewer когда будет добавлена поддержка логов?

В предыдущих issue писали что вечером появится

**Comment by yndx-shri-reviewer** [comment]
@SkyFlame00 сегодня вечером должны появиться.

@kaban270790 тожно не нужно. Мы сохраняем только разницу между вашей версткой и эталонной. Если ее нет, то это означает, что либо там всё правильно, и тест прошёл, либо функция шаблонизации упала с ошибкой, логи которой будут отображаться в интерфейсе.

**Comment by bo4arovpavel1989** [comment]
Разбирался с проблемой запуска шаблонизатора и ради эксперимента изменил код на такой
![Screenshot_2019-07-16 bo4arovpavel1989 ya-shri-1](https://user-images.githubusercontent.com/23580188/61325082-9d1d3b00-a81c-11e9-8463-e3d47a9de724.png)  

поскольку в этом коде падать нечему, то по идее у меня в репозитории должны были появиться скриншоты, однако я их не нашел, что я делаю не так?

**Comment by kaban270790** [comment]
@yndx-shri-reviewer Возник такой вопрос, как происходит формирование эталонного (правого) изображения, он так же генерится на основе эталонных стилей или просто подается изображение?
Объясняю почему такой вопрос: У меня не появляется переключатель тем, хотя у него физические размеры, и хоть где-то он должен показать свой вид ))
![image](https://user-images.githubusercontent.com/27147261/61325391-47955e00-a81d-11e9-8c29-03d1ca399eae.png)

**Comment by vaiil** [comment]
@yndx-shri-reviewer 
Присоединяюсь к вопросу @kaban270790 
Также есть вопрос по блоку payment: похоже что к кнопке не применяется модификатор с размером 
И по блоку history, похоже что не миксуется элемент e-accordion__more к history__hide

**Comment by vaiil** [comment]
@bo4arovpavel1989 
У меня была проблема, что я компилировал webpack-ом (настроенным под подготовку скриптов для веба) файл шаблонизатора, в результате чего на выходе получал код, который нода не могла импортировать. 

Скриншоты если что появляются в отдельной ветке.

**Comment by SkyFlame00** [comment]
@kaban270790 попробовал собрать вебпаком: нода импортирует (в другой конфигурации и в браузере работает). Смотря какая, конечно, конфигурация. Но какая может быть ошибка - не ясно абсолютно. Тем более что экспорт идет точно в соответствии с указаниями и файл размещен в папке build. Причем что функция даже внешние зависимости не использует. Тем временем логов до сих пор нет

**Comment by kaban270790** [comment]
@SkyFlame00 проверь script.js

**Comment by yndx-shri-reviewer** [comment]
@kaban270790 Проверили эталонные json'ы, на основании которых генерируются изображения. Там блок onoffswitch присутствует и описан правильно.

@vaiil Поправили. Спасибо

**Comment by bo4arovpavel1989** [comment]
> 
> 
> @SkyFlame00 проверь script.js

подтверждаю, сейчас удалил свой script.js, вместо него сделал заглушку и скрины появились

**Comment by danilstoyanov** [comment]
> > @SkyFlame00 проверь script.js
> 
> подтверждаю, сейчас удалил свой script.js, вместо него сделал заглушку и скрины появились

то есть функция шаблонизации теперь отрабатывает нормально, и проблема была в script.js?

**Comment by bo4arovpavel1989** [comment]
> 
> 
> > > @SkyFlame00 проверь script.js
> > 
> > 
> > подтверждаю, сейчас удалил свой script.js, вместо него сделал заглушку и скрины появились
> 
> то есть функция шаблонизации теперь отрабатывает нормально, и проблема была в script.js?

Вроде отрабатывает, хотя скрины появились только для страницы index, а на остальные страницы нет и тесты по ним не прошли

**Comment by danilstoyanov** [comment]
> > > > @SkyFlame00 проверь script.js
> > > 
> > > 
> > > подтверждаю, сейчас удалил свой script.js, вместо него сделал заглушку и скрины появились
> > 
> > 
> > то есть функция шаблонизации теперь отрабатывает нормально, и проблема была в script.js?
> 
> Вроде отрабатывает, хотя скрины появились только для страницы index, а на остальные страницы нет и тесты по ним не прошли

Подтверждаю, если файл script.js пуст, то функция отрабатывает и скриншоты появляются, правда только для index страницы

**Comment by yndx-shri-reviewer** [comment]
Мы добавили вывод логов ошибок в папку /logs аналогично скриншотам.
