### ISSUE TITLE
Логи для ошибки в функции-шаблонизаторе

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#79]
@SkyFlame00 сегодня вечером должны появиться.

@kaban270790 тожно не нужно. Мы сохраняем только разницу между вашей версткой и эталонной. Если ее нет, то это означает, что либо там всё правильно, и тест прошёл, либо функция шаблонизации упала с ошибкой, логи которой будут отображаться в интерфейсе.

_Originally posted by @yndx-shri-reviewer in https://github.com/yndx-shri-reviewer/task-1/issues/78#issuecomment-511953876_

Вчера один из организаторов сказал, что вечером должны будут появится логи с ошибками, но видимо не успели их выкатить 16 числа :(

Стоит ли ждать логи сегодня?

**Comment by yndx-shri-reviewer** [comment]
Сделали сохранение логов. Сохраняются аналогично изображениям в папке logs.
