### ISSUE TITLE
Элемент блока "History"

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#8]
![image](https://user-images.githubusercontent.com/18240896/59562614-5bd81680-9037-11e9-9cee-bae9443864a1.png)
Скажите пожалуйста, это декоративный элемент?
Или же здесь нужно использовать text и два word?

**Comment by yndx-shri-reviewer** [comment]
Это текст, не декоративный элемент

**Comment by danilstoyanov** [comment]
Да, всем вновь прибывшим в данный issue:
Было обновление спецификации компонента history, там это объясняется:
![image](https://user-images.githubusercontent.com/18240896/59981797-77cc5100-9611-11e9-97b7-501cdc78c00f.png)
