### ISSUE TITLE
Может ли функция шаблонизации принимать массив?

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#80]
Собственно, может ли она принимать массив или достаточно только объекта?

На мысль о массиве меня навело описание из второго задания, где заголовки задаются в массивах (они отдельные корневые объекты или нет?):
```
[
    {
        "block": "text",
        "mods": { "type": "h1" }
    },

    // неправильно
    {
        "block": "text",
        "mods": { "type": "h1" }
    }
]
```

**Comment by yndx-shri-reviewer** [comment]
В наших тестах будет передаваться объект на вход. Внутри объектов в content массивы, конечно, будут.
