### ISSUE TITLE
Блок Warning: Не соответствие описания скриншоту

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#81]
На что ориентироваться на скриншот или описание?
1. В описании [контентного блока](https://github.com/yndx-shri-reviewer/task-1/blob/master/CONTENT.md) `warning` указано: 
```
Исходные стили:
минимальная высота — 335px;
```
но судя по скриншоту она должна быть `356px`

2. У блока placeholder указаны внешний отступ - `m`, но не указано с помощью какого микса/модификатора он должен назначаться.
```
Исходные стили:
размер внешних вертикальных отступов вложенного блока placeholder — m.
```
Это стили исключительно блока `warning` и все блоки `placeholder` будут иметь там отступ `m`?
3. Кажется скриншот, неправильно обрезан - все границы должны быть `2px`, однако правая граница тоньше.
4. У блока `text` существует модификатор `.text_align_center` нужно ли его использовать в блоке `warning`

**Comment by SkyFlame00** [comment]
335 - мобильная версия, 356 - десктоп. По скриншотам только удалось увидеть

**Comment by yndx-shri-reviewer** [comment]
1. Это минимальная высота. Фактическая может быть больше.
2. Это стили только блока warning, и мы не навешиваем дополнительный модификатор на placeholder.
3. Такое случается с хромом при создании скриншотов. При тестировании это не будет влиять на результат.
4. Да, нужно. Добавили в описание. Спасибо
