### ISSUE TITLE
Не хватает отступов между секциями

### ISSUE THREAD

**Issue by GumerShag** [yndx-shri-reviewer/task-1#82]
Добрый день!

Есть подозрение, что в секциях контейнеров не добавляется модификатор отступов **indent-b_xxl/xxxl**. Структура страниц получается верная, но явно не хватает отступов между секциями. Проверьте пожалуйста.

![index_gum](https://user-images.githubusercontent.com/10955085/61454175-cb0f9600-a968-11e9-8c74-e412fd3c8fb7.png)

**Comment by yndx-shri-reviewer** [comment]
В описании страницы index указан вертикальный отступ.

![image](https://user-images.githubusercontent.com/50715001/61454413-889a8900-a969-11e9-9b95-35ebc8c5e165.png)
