### ISSUE TITLE
Отсутствует input в элементе form control

### ISSUE THREAD

**Issue by ValeraS** [yndx-shri-reviewer/task-1#83]
Добрый день!

Проверьте, пожалуйста. Судя по расхождениям в скриншотах, в элементе `form control` блока `payment` отсутствует блок `input`

**Comment by danilstoyanov** [comment]
Тоже столкнулся с отсутствием инпута

**Comment by vaiil** [comment]
У меня корректно (на момент сегодняшнего утра):
![index_desktop_block_payment](https://user-images.githubusercontent.com/3755615/61458322-e97a8f00-a972-11e9-97fd-40d9b16ac516.png)
Но вот кнопка растягивается на всю ширину.

**Comment by kaban270790** [comment]
У меня тоже инпуты не появляются, и сразу кнопка растянута была, пришлось править свой json и подгонять стили. А вот инпуты так не появились ((

**Comment by yndx-shri-reviewer** [comment]
> Добрый день!
> 
> Проверьте, пожалуйста. Судя по расхождениям в скриншотах, в элементе `form control` блока `payment` отсутствует блок `input`

Проверили. Все на месте

**Comment by vaiil** [comment]
@yndx-shri-reviewer По кнопке тоже все ок? По спецификации она - вложенный элемент без миксов с модом на размер. В json-е также?

**Comment by kaban270790** [comment]
@vaiil у меня кнопка норм

**Comment by ValeraS** [comment]
@yndx-shri-reviewer Как ни странно, но я так и не нашел базовый блок `input` в контентном блоке `payment`. Делал блоку `input` абсолютное позиционировани, фиксированные размеры, красил в различные цвета фон и границу. И в результате он так и не появился на скриншотах. Там именно блок `input` используется в вашей реализации?
```js
{
	"block": "input"
	"mod": { "size": "l" }
}
```

**Comment by danilstoyanov** [comment]
Тоже отсутствуют инпуты и кнопки.

**Comment by yndx-shri-reviewer** [comment]
Проверили и перезалили json'ы. Проверьте, пожалуйста, остались ли проблемы с инпутами.

**Comment by SkyFlame00** [comment]
@yndx-shri-reviewer у меня появилась проблема с input в блоке payment (он не растягивается). Вчера еще все работало, но сегодня уже не работает. Делал изменения в верстку, но стили инпутов и их родителей они не затрагивали

![index_desktop_block_payment](https://user-images.githubusercontent.com/7037108/61545671-ae4e8d80-aa50-11e9-83ce-8af800f134af.png)

**Comment by danilstoyanov** [comment]
> @yndx-shri-reviewer у меня появилась проблема с input в блоке payment (он не растягивается). Вчера еще все работало, но сегодня уже не работает. Делал изменения в верстку, но стили инпутов и их родителей они не затрагивали
> 
> ![index_desktop_block_payment](https://user-images.githubusercontent.com/7037108/61545671-ae4e8d80-aa50-11e9-83ce-8af800f134af.png)

у меня примерно из того же рода проблема
положение кнопки поехало)

**Comment by yndx-shri-reviewer** [comment]
@danilstoyanov @SkyFlame00 у нас, исходя из спецификации блока form, в form__item вкладываются form__label и form__control. Проверьте их стили.

**Comment by SkyFlame00** [comment]
@yndx-shri-reviewer да, у меня не был вложен form__control. Уже все работает
