### ISSUE TITLE
Некорректный цвет brand-logo megafon

### ISSUE THREAD

**Issue by ValeraS** [yndx-shri-reviewer/task-1#84]
В css используется цвет `#33c778` для megafon и он не проходит проверку.

![image](https://user-images.githubusercontent.com/10867286/61458202-9b658b80-a972-11e9-9085-567f88ccab51.png)
![image](https://user-images.githubusercontent.com/10867286/61458215-a9b3a780-a972-11e9-8e42-4da85bce1183.png)

**Comment by yndx-shri-reviewer** [comment]
Поправили. Спасибо
