### ISSUE TITLE
Блок Product: Микс инверсированной темы

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#85]
В описании блока [product](https://github.com/yndx-shri-reviewer/task-1/blob/master/CONTENT.md#%D1%81%D0%BC%D1%8B%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA-product) указано, что к элементу `product__image` миксуется блок `theme` с модификатором `color`
```
Примиксованные блоки паттернов
product__image (theme_color_project-inverse или theme_color_project-default)
```
Для того, что бы инверсировать и фон изображения и фон карточки `product` и цвет текста, нужно миксовать тему, блоку `product`, а не элементу `image`.

**Comment by yndx-shri-reviewer** [comment]
Вам необходимо реализовать решение в том виде, как указано в задании. Это сделано специально, чтобы уменьшить вероятность ошибки при проверке задания автотестами.
