### ISSUE TITLE
Страница Product. Отступ между заголовком и блоками во второй секции.

### ISSUE THREAD

**Issue by ValeraS** [yndx-shri-reviewer/task-1#86]
@yndx-shri-reviewer
По описанию страницы Product у нее есть
```
 отступ между заголовком и блоками во второй секции — xxl;
```
Как мне кажется, это должно быть реализовано заворачиванием заголовка в блок `section` или елемент `layout__container` c модификатором `indent-b_xxl`. Но в вашей реализации это не так. Это ошибка?

**Comment by GumerShag** [comment]
Вот тут они ответили https://github.com/yndx-shri-reviewer/task-1/issues/82

**Comment by ValeraS** [comment]
@GumerShag Это другое, впросов к отступам на странице `index` у меня нет, там все нормально.

**Comment by yndx-shri-reviewer** [comment]
@ValeraS используйте для этого заголовка микс product__title. Добавили его в условие.
section для этого не очень хорошо подходит, т.к. section призван отделять большие смысловые блоки, а заголовок к таковым не относится.
