### ISSUE TITLE
Картинки

### ISSUE THREAD

**Issue by quadratos** [yndx-shri-reviewer/task-1#87]
Наверное, глупый вопрос, но как вставлять картинки-заглушки?
Я понимаю, что это в background-image, но какой должен быть путь? Просто image-placeholder-primary.svg?

**Comment by quadratos** [comment]
И надо ли добавлять build?

**Comment by vaiil** [comment]
Я вставлял через data:image в css файл

**Comment by SkyFlame00** [comment]
@vaiil аналогично делал
