### ISSUE TITLE
Страница Content

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#89]
Страница content.html, полностью отсутвуют текстовые блоки, кроме заголовков, подскажите пожалуйста нету ли ошибки в тестовых входных данных? На всех остальных страницах текстовые блоки рендерятся 
![content_desktop](https://user-images.githubusercontent.com/20458127/61476265-4f780e00-a995-11e9-873d-0d94cb3bf73a.png)

**Comment by shishkinilya** [comment]
Может есть те, у кого на этой странице все ок, отпишите плиз, что бы искать проблему у себя)

**Comment by ValeraS** [comment]
@shishkinilya У меня на этой странице всё нормально.

**Comment by shishkinilya** [comment]
@ValeraS спасибо

**Comment by SemenovaEkaterina** [comment]
Столкнулась с аналогичной проблемой. Подскажите, пожалуйста, на вход функции шаблонизации для текстовых блоков слова всегда подаются как массив объектов с указанным модификатором `width`? Или нужно уметь парсить строки вида `l + m + m + s + m + m + m + s + m...`?

**Comment by chrstnv** [comment]
И у меня такая же, текста нет вообще.

**Comment by shishkinilya** [comment]
@SemenovaEkaterina согласно описанию полей bemjson, https://ru.bem.info/technologies/classic/bemjson/#content, в поле content у блока может быть объект { html: string } где string - строка с html разметкой, я сначала это проглядел, потом допилил функцию шаблонизацию и мне это всё равно не помогло)) все равно текстовых блоков нету, хотя локально функция отрабатывает в случае с передачей в content строки с html разметкой. @ValeraS а вы не подскажете у вас реализована в функции шаблонизации возможность указать у блока в поле content объект { html: string }?

**Comment by SemenovaEkaterina** [comment]
@shishkinilya шла таким же путем, тоже добавила поддержку поля  `html`, но это ничего не поменяло)
У меня отсутствует тест на страницах `product` и `content`, причем только тот, который содержит большое число слов, заголовки и текст в других блоках отображаются корректно.
Вот и я думаю, что может быть абзацы текста, где много слов, как-то иначе задаются на вход.

**Comment by danilstoyanov** [comment]
Здравствуйте ребята.
Тоже столкнулся с проблемой рендеринга текстовых блоков на страницах product и content.
Выглядит это следующим образом:
![content](https://user-images.githubusercontent.com/18240896/61522073-44b38c80-aa1a-11e9-91d5-0fddf7ef0e63.jpg)
![Untitled-4](https://user-images.githubusercontent.com/18240896/61522077-4715e680-aa1a-11e9-9107-87e2b5807d20.jpg)

Также, отсутствует блок onoffswitch на главной странице.

**Comment by ValeraS** [comment]
@shishkinilya свойство `html` у меня не поддерживается.

**Comment by SkyFlame00** [comment]
У меня отображается текст на всех страницах. Везде блоки выглядят примерно так:

```
{
  block: 'text',
  mods: {
    'view': 'primary',
    'size': 'xxl',
    'type': 'h1'
  },
  content: [
    {
      block: 'text',
      elem: 'word',
      elemMods: { 'width': 'm' }
    },
    ...
  ]
}
```

**Comment by yndx-shri-reviewer** [comment]
> У меня отображается текст на всех страницах. Везде блоки выглядят примерно так:
> 
> ```
> {
>   block: 'text',
>   mods: {
>     'view': 'primary',
>     'size': 'xxl',
>     'type': 'h1'
>   },
>   content: [
>     {
>       block: 'text',
>       elem: 'word',
>       elemMods: { 'width': 'm' }
>     },
>     ...
>   ]
> }
> ```

У нас в json аналогичным образом задаются.

**Comment by danilstoyanov** [comment]
Хм, может проблема в реализации с точки зрения стилевого оформления? (но это очень сомнительно)
@shishkinilya @chrstnv @SemenovaEkaterina ребята, у вас комбинация text+ word при помощи flexbox реализована?

**Comment by SkyFlame00** [comment]
@danilstoyanov я, кстати, переделал с flexbox'ов на inline-block. Судя по всему, именно по этой причине у меня проблема с 4px (#88). Спасибо :D

**Comment by danilstoyanov** [comment]
> @danilstoyanov я, кстати, переделал с flexbox'ов на inline-block. Судя по всему, именно по этой причине у меня проблема с 4px (#88). Спасибо :D

не за что <3

самое обидное, что я тоже реализовал всё через inline-block, и у меня ничего не видно :D

**Comment by shishkinilya** [comment]
@danilstoyanov да, флексом

**Comment by SkyFlame00** [comment]
> > @danilstoyanov я, кстати, переделал с flexbox'ов на inline-block. Судя по всему, именно по этой причине у меня проблема с 4px (#88). Спасибо :D
> 
> не за что <3
> 
> самое обидное, что я тоже реализовал всё через inline-block, и у меня ничего не видно :D

А у меня наоборот работает, но вот есть отступ в 4px, который пришлось подгонять. Главное, что у меня в браузере все нормально, никакого отступа нет, а на машине для автотестов есть. Вот я и забыл, что у инлайн-блоков отступы справа и снизу есть.

**Comment by SemenovaEkaterina** [comment]
@danilstoyanov 
inline-block
Не думаю, что проблема в стилях, потому что судя по отсутствию margin у блока текст на картинке, его просто нет.
Скорее всего какие-то недоработки в функции шаблонизации.

**Comment by quadratos** [comment]
> @danilstoyanov
> inline-block
> Не думаю, что проблема в стилях, потому что судя по отсутствию margin у блока текст на картинке, его просто нет.
> Скорее всего какие-то недоработки в функции шаблонизации.

Но остальной же текст она рендерит, не могут же они совсем по-разному подавать эти текстовые блоки в разных местах

**Comment by chrstnv** [comment]
> Также, отсутствует блок onoffswitch на главной странице.

И такая проблема у меня тоже есть. Мозг сломала уже, двадцать раз перепроверила по спецификации все названия блоков и элементов, не понимаю, почему не видно. Может, тоже какой-то косяк стилей или шаблонизации... Грешила на js (у меня переключение скриптом реализовано), думала мало ли, но и эта гипотеза провалилась.
А у кого-нибудь видно переключатель тем?

**Comment by chrstnv** [comment]
Ой, простите за дезинформацию, кажется, он полечился после перезаливки json...

**Comment by chrstnv** [comment]
@ValeraS, а вы использовали готовое решение для шаблонизации или свое писали, если не секрет?

**Comment by chrstnv** [comment]
Ребят, у меня появились все блоки после учета вот этого кейса:
https://github.com/yndx-shri-reviewer/task-1/issues/95
