### ISSUE TITLE
Блок "Сommercial"

### ISSUE THREAD

**Issue by danilstoyanov** [yndx-shri-reviewer/task-1#9]
![image](https://user-images.githubusercontent.com/18240896/59562782-90e56880-9039-11e9-8a78-57f51eeb6117.png)
Когда мы смотрим на дизайн карточки commercial, мы видим что буллиты сделаны как обычные слова минимального размера. Получаются "квадратики".
В дизайне страницы, они выглядят как круглые буллиты
![image](https://user-images.githubusercontent.com/18240896/59562803-c25e3400-9039-11e9-9308-69fa0e583532.png)
Какие нужно использовать в итоге?

**Comment by bo4arovpavel1989** [comment]
Добавлю: в спецификации указано - высота изображения 180px, box-sizing: border-box, однако на скриншоте отл
![Screenshot_2019-06-20 Screenshot](https://user-images.githubusercontent.com/23580188/59855908-91099f00-937e-11e9-95fa-1ee0d36d0e7c.png)
![123](https://user-images.githubusercontent.com/23580188/59855911-936bf900-937e-11e9-941a-cbfc11789ea9.jpg)

ичается

**Comment by yndx-shri-reviewer** [comment]
1. Должны  быть квадраты . В  дизайне страницы ошибка,  поправим
2. Спасибо  большое за вопрос, мы уточним и ответим на него в ближайшие несколько  дней

**Comment by yndx-shri-reviewer** [comment]
Спасибо за вопрос. Мы обновили скриншоты и описание блока.
