### ISSUE TITLE
Микс у блока warning

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#90]
На блок warning у вас точно theme_color_project-warning навешивается?

У меня такой код, у себя на сервере все нормально примешивается и отображается (оранжевый и белая рамка):

```
<div class="warning informer informer_view_default informer_border_all theme theme_color_project-warning">
...
```

Однако автотесты выдают такой скрин (хотя текст белый, как положено):

![index_desktop_block_warning](https://user-images.githubusercontent.com/7037108/61487890-970b9380-a9af-11e9-967c-112687f0647e.png)

Да, если вручную задать в warning оранжевый цвет и белую рамку, то тест по этому блоку пройдет.

**Comment by danilstoyanov** [comment]
Тоже такая проблема есть

**Comment by chrstnv** [comment]
+1, тоже костылем полечила :(

**Comment by yndx-shri-reviewer** [comment]
Мы проверили и перезалили json'ы. Проверьте, пожалуйста.

**Comment by SkyFlame00** [comment]
Теперь вроде работает. Спасибо
