### ISSUE TITLE
Безымянный заголовок в product.html

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#91]
Во что должен вкладываться этот белый заголовок, из-за которого не удается пройти тест? Или нужно как-то захардкодить переопределением?

![product_desktop](https://user-images.githubusercontent.com/7037108/61489133-ac35f180-a9b2-11e9-9608-7c5c05742cdd.png)

**Comment by yndx-shri-reviewer** [comment]
Используйте микс product__title. Добавили его в описание страницы.
