### ISSUE TITLE
Ошибка в блоке collect

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-1#92]
Не проходят блоки collect по двум приколам, которых я не вижу. Если наложить правый блок на левый, то они совпадут. Помогите, пожалуйста, понять, в чем дело

![collect_desktop_block_collect](https://user-images.githubusercontent.com/7037108/61489420-5a419b80-a9b3-11e9-96c4-81d0152bb5e2.png)

![collect_mobile_block_collect](https://user-images.githubusercontent.com/7037108/61489426-5b72c880-a9b3-11e9-8e1e-5fdf98b6873d.png)

**Comment by SemenovaEkaterina** [comment]
Может быть не тот цвет?
В задании указан `#0070f0` и справа на скрине такой же.
А слева `#1872f2`

**Comment by SkyFlame00** [comment]
@SemenovaEkaterina действительно! Спасибо большое, блок прошел
