### ISSUE TITLE
Не вижу скриншотов в автотестах

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#93]
Заметил, что участники создают `issue` в которых ссылаются на скриншоты из результатов автотестов. Тем не менее я вижу только это:
![scrn](https://user-images.githubusercontent.com/26760449/61554038-6db53b00-aa75-11e9-9eea-9be7419851a5.png)

Не подскажете с чем это может быть связано?

Лично мне кажется, что дело в том, что функция шаблонизации не смогла запустится.
Я использую систему модулей `commonjs`:
```
module.exports = function(obj) {}
```
_Здесь сказали , что так можно @yndx-shri-reviewer in https://github.com/yndx-shri-reviewer/task-1/issues/55#issuecomment-509826346_

Если проблема в этом, не могли бы подсказать подробнее как именно испортируется фукция шаблонизации, чтобы избежать ошибок?

**Comment by danilstoyanov** [comment]
Единственное, что могу посоветовать - на время положить в директорию `build` пустой `script.js` и попробовать прогнать автотесты.

Саму функцию шаблонизации можно экспортировать как в задании написано.
`export default function(obj) {...}`

Трюк со скриптом помог мне. По крайней мере, появилась возможность посмотреть что там собирается на стороне проверяющей машины)

**Comment by WIVSW** [comment]
> Единственное, что могу посоветовать - на время положить в директорию `build` пустой `script.js` и попробовать прогнать автотесты.
> 
> Саму функцию шаблонизации можно экспортировать как в задании написано.
> `export default function(obj) {...}`
> 
> Трюк со скриптом помог мне. По крайней мере, появилась возможность посмотреть что там собирается на стороне проверяющей машины)

Спасибо, за совет. Увидел, что у меня логи ошибок в репозитории появились, будем разбираться:)
