### ISSUE TITLE
Продление срока подачи заявок

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-1#94]
Уважаемые, организаторы, хотелось бы обсудить возможность продления сроков подачи заявок. 

Технически, насколько это было возможно, я закончил первое задание вовремя и начал заниматься остальными. Потом какое-то время я им не занимался в виду практически невозможного дебага (ждали пока выкатят скриншоты) + добавим сюда большое количество исправлений в условиях, которые тоже требуют актуализации исходного кода решения.

Думаю, эта ситуация затронула многих и время выполнения первого задания растянулось в разы по сравнению с запланированным. В связи с этим хотелось бы узнать - можем ли мы расчитывать на дополнительные несколько дней?

**Comment by yndx-shri-reviewer** [comment]
Мы продлили срок сдачи работ до 29 июля
