### ISSUE TITLE
Нет кнопки переключения кнопки в index.html

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-1#95]
Судя по всему не хватает кнопки переключателя тем во вводных данных, как минимум на мобильной версии `index.html` и декстопной `index.html`. Можете проверить?
![no_switcher](https://user-images.githubusercontent.com/26760449/61576495-45205600-aaf4-11e9-83d9-9be384bd0811.png)

**Comment by SkyFlame00** [comment]
Сегодня я еще не проверял, но вчера у меня все работало

**Comment by WIVSW** [comment]
> Сегодня я еще не проверял, но вчера у меня все работало

Ну, я локально проверял, за пределы экрана кнопка не могла вылезти, максимум перенестись на следующую строку, но на скриншоте кнопки нет вообще.

**Comment by Hakkoid** [comment]
Возможно вы обрабатываете не все возможные варианты значений поля content

**Comment by quadratos** [comment]
Ощущение, что на днях изменили джейсоны, потому что страница index проходила еще вчера, а теперь опять не видно переключатель

**Comment by WIVSW** [comment]
> Ощущение, что на днях изменили джейсоны, потому что страница index проходила еще вчера, а теперь опять не видно переключатель
> <img alt="Снимок экрана 2019-07-20 в 14 56 36" width="702" src="https://user-images.githubusercontent.com/52795963/61578378-a2b9a000-aafe-11e9-8e28-c4f8e8dc7e81.png">
> <img alt="Снимок экрана 2019-07-20 в 14 56 23" width="573" src="https://user-images.githubusercontent.com/52795963/61578379-a3523680-aafe-11e9-8669-d8a86e79f8f9.png">

Спасибо @Hakkoid , попробовал обрабатывать такой блок:
```
{
    block: 'some',
    content: [
        {
            block: 'other',
        },
        [
            {
                block: 'another',
            },
        ],
    ],
}
```
И заработало.

**Comment by neuspeed** [comment]
Так и не смог понять как в content массиве могут быть вложены и массивы и объекты. Одно дело когда внутри контента один блок, тогда понятно. А вот и массивы и объекты...
