### ISSUE TITLE
Задание ушло на проверку преподавателям автоматически

### ISSUE THREAD

**Issue by chrstnv** [yndx-shri-reviewer/task-1#96]
У меня прошли автотесты, и задание автоматически ушло на проверку преподавателю, без подтверждения. Не является ли это ошибкой? Я рассчитывала сделать еще рефакторинг, но теперь непонятно, как это сделать безопасно: ведь автотесты теперь повторно не запустить :(
Есть ли какое-то решение этой проблемы?

**Comment by SkyFlame00** [comment]
Можно, в итоге-то?

**Comment by dima117** [comment]
Запустить через личный кабинет нельзя. Можно контролировать только самостоятельно (например, написав собственные автотесты с помощью любого инструмента).

Также сейчас вы можете быть уверены, что преподаватель посмотрит ваше задание, даже если при рефакторинге что-то сломается.

**Comment by SkyFlame00** [comment]
@dima117 то есть преподаватели будут смотреть версию, которая прошла автотесты, а также последний коммит, сделанный до конца времени подачи заявок?

**Comment by chrstnv** [comment]
@SkyFlame00  я так поняла, что преподавателю придет ссылка на твой репозиторий, и смотреть  его будут в том виде, в котором он на данный момент, а не в том, в котором оно было, когда автотесты прошли. Это хорошо, постараюсь ничего не разломать :) @dima117 , спасибо большое за ответ.
