### ISSUE TITLE
Шаблонизатор и стили

### ISSUE THREAD

**Issue by burlaknastia** [yndx-shri-reviewer/task-1#97]
Добрый вечер! Возможно уже очень сильно запуталась, но очень хочется понять как добавлять стили в шаблонизаторы, например bem-xjst. Особенно, с учетом того, что в итоговой разметке не должно быть тегов header и прочего. Заранее спасибо!

**Comment by shlensky** [comment]
Никак. Просто положите файл style.css в папку build, при прогоне автотестов его подключат на страницу автоматически.

**Comment by yndx-shri-reviewer** [comment]
да, @shlensky правильно ответил
