### ISSUE TITLE
Страница collect.html

### ISSUE THREAD

**Issue by shishkinilya** [yndx-shri-reviewer/task-1#99]
Подскажите пожалуйста, есть ли в исходных данных у секции с черным фоном модификатор space-v?
![collect_desktop](https://user-images.githubusercontent.com/20458127/61588350-b3bbed00-aba2-11e9-9a98-30e24b5b1694.png)

Тест страницы product.html, где есть аналогичная секциия, прошел
![product](https://user-images.githubusercontent.com/20458127/61588398-7146e000-aba3-11e9-9ab7-a718aabc67cd.png)
![Screenshot from 2019-07-21 10-37-54](https://user-images.githubusercontent.com/20458127/61588410-a6533280-aba3-11e9-8042-6b0123adc797.png)

**Comment by yndx-shri-reviewer** [comment]
Там space-v_xxxxxl, как описано в условии: https://github.com/yndx-shri-reviewer/task-1/blob/master/PAGES.md
